### ISSUE TITLE
MonitorHost not working on non english Windows OS

### ISSUE THREAD

**Issue by tlegras** [jamesoff/simplemonitor#10]
On non english windows OS MonitorHost will not work as output of ping is language dependant.
Ex, in French:

```
C:\Users\tlegras>ping -n 1 -w 5000 127.0.0.1

Envoi d'une requête 'Ping'  127.0.0.1 avec 32 octets de données :
Réponse de 127.0.0.1 : octets=32 temps<1ms TTL=128

Statistiques Ping pour 127.0.0.1:
    Paquets : envoyés = 1, reçus = 1, perdus = 0 (perte 0%),
Durée approximative des boucles en millisecondes :
    Minimum = 0ms, Maximum = 0ms, Moyenne = 0ms

C:\Users\tlegras>ping -n 1 -w 5000 128.0.0.1

Envoi d'une requête 'Ping'  128.0.0.1 avec 32 octets de données :
Réponse de 192.168.169.254 : Impossible de joindre le réseau de destination.

Statistiques Ping pour 128.0.0.1:
    Paquets : envoyés = 1, reçus = 1, perdus = 0 (perte 0%),

```

Unfortunatly I don't have any solution that would work on any windows workstation. solution could be to make MonitorHost.ping_regexp configurable. in my case in network.py line 172 change : 
`self.ping_regexp = "Reply from "`
with 
`self.ping_regexp = "Réponse de "`
(caution to encoding...)

**Comment by jamesoff** [comment]
Interesting, didn't realise output of ping was localised, but it's obvious now you say it!

I guess making it a configuration option is the only way, other than finding another way to send pings without relying on ping as an external command.

**Comment by tlegras** [comment]
Maybe a possibility to check ping result [here](http://stackoverflow.com/questions/3050898/how-to-check-if-ping-responded-or-not-in-a-batch-file/3485344#3485344).

**Comment by danieleteti** [comment]
The same problem exists for "service" monitor where the regex looks for "STATE" (in my italian Windows box always fails).

**Comment by danieleteti** [comment]
I dont' know if it is feasible on other languages, but this could works.

```shell
C:\Tools\simplemonitortest
λ sc query "PostgreSQL 11.0-1 Server" state=all

NOME_SERVIZIO: PostgreSQL 11.0-1 Server
        TIPO                   : 10  WIN32_OWN_PROCESS
        STATO                  : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        CODICE_USCITA_WIN32    : 0  (0x0)
        CODICE_USCITA_SERVIZIO : 0  (0x0)
        PUNTO_CONTROLLO          : 0x0
        INDICAZIONE_ATTESA     : 0x0

```

The 3rd lines in the output should be always "STATE" related. So, considering that the state is always in english, we could try to find "RUNNING" in the 3rd line to check if the service is actually running.

Or, if you don't want to change the current detection mechanism, the engine could run this command line at the first loop just to find how the word "STATE" is in the current language, and then use that word in the regex.


Just my2 cents
