### ISSUE TITLE
Docker-Compose fails

### ISSUE THREAD

**Issue by R4R3Dev** [jamesoff/simplemonitor#101]
A freshly cloned copy of simplemonitor fails on  while "docker-compose build".

+ Error Message
Collecting cffi>=1.7 (from cryptography>=2.2.1->pyopenssl->-r /usr/src/app/simplemonitor/requirements.txt (line 2))
Downloading https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz (438kB)
Complete output from command python setup.py egg_info:
unable to execute 'gcc': No such file or directory
unable to execute 'gcc': No such file or directory
No working compiler found, or bogus compiler options passed to
the compiler from Python's standard "distutils" module.  See
the error messages above.  Likely, the problem is not related
to CFFI but generic to the setup.py of any Python package that
tries to compile C code.  (Hints: on OS/X 10.8, for errors about
-mno-fused-madd see http://stackoverflow.com/questions/22313407/
Otherwise, see https://wiki.python.org/moin/CompLangPython or
the IRC channel #python on irc.freenode.net.)
Command "python setup.py egg_info" failed with error code 1 in /var/tmp/pip-install-aSxEnT/cffi/
ERROR: Service 'simplemonitor' failed to build: The command '/bin/sh -c pip install --no-cache-dir -r ${SRC}/requirements.txt' returned a non-zero code: 1

+ Docker-Version:
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017

**Comment by RDev-AT** [comment]
I am on it to rewrite the docker-script. 
+ .Dockerfile
+ .docker-compose.yml
+ start.py

It is written in a (imho) strange way.

**Comment by jamesoff** [comment]
Thanks! While I've run the odd container, Docker is not my area of expertise.

If you're able to supply a script which could validate the build (would just `docker-compose build` do it?) that'd be good to include in Travis.

**Comment by jamesoff** [comment]
Thanks, I'll check it out!

I'm planning on ditching Python 2.7 soon but I wanted to get one more release out with support for it as I've fixed a lot of issues recently. After that I'll remove 2.x support and fix up the workarounds for compatibility :)

**Comment by RDev-AT** [comment]
*) branch: https://github.com/RDev-AT/simplemonitor/tree/feature/docker-support

**Comment by jamesoff** [comment]
I've created a PR for your branch to remind me to look at it properly when I have time :)

**Comment by jamesoff** [comment]
Closing as this was merged by #103
