### ISSUE TITLE
Use pyping module

### ISSUE THREAD

**Issue by jamesoff** [jamesoff/simplemonitor#102]
We should attempt to use the pyping module which would fix the problems of trying to parse `ping`'s output, especially in different locales (e.g. #10)

**Comment by jamesoff** [comment]
For anyone playing along at home, I tried a Python module to do ping, but that now means SimpleMonitor needs to run as root. I'm pondering if that's a requirement I want to impose, or if there's other options (like fping) to use instead.

**Comment by wsw70** [comment]
Since `simplemonitor` can do recovery it is likely it will be running as root anyway.
So my vote is that this is not a blocking requirement.

**Comment by mikebro19** [comment]
> For anyone playing along at home, I tried a Python module to do ping, but that now means SimpleMonitor needs to run as root. I'm pondering if that's a requirement I want to impose, or if there's other options (like fping) to use instead.

Could you include some config to tell monitor how to parse the ping e.g. regex to find response time or timeout etc

**Comment by jamesoff** [comment]
Yeah, this is already a thing done inside the monitor so it could be exposed to let people set custom regexes if needed.

My feeling is that I shall keep the existing code (possibly with that addition) to avoid surprising anyone expecting it, and then enable the new (requires-root but hopefully better) version by specifying an option, or maybe `type=ping2` or similar.
