### ISSUE TITLE
Memory consumption (using Python3)

### ISSUE THREAD

**Issue by cpina** [jamesoff/simplemonitor#104]
I can see how simplemonitor keeps using more and more memory. After running it uses (ps auxw | grep -i monitor.py):
`carles   24308 12.1  2.7  80264 28012 pts/3    S+   00:05   0:01 python3 monitor.py`
But after 3 weeks:
`carles    7648  7.8  5.0 323404 51472 pts/3    S+   Jun28 2694:59 python3 monitor.py` 

This causes in this small VPS server failures of monitors with this line in the email:
`Additional info: [Errno 12] Cannot allocate memory`

In this server I have 11 monitors:
 * 3 host
 * 3 http
 * 1 diskspace
 * 4 command

I've only noticed it because the low available memory in the server. It confused me once wondering who was using the "Cannot allocate memory" only to see that was the monitoring system :-)

The monitor interval is 5 seconds, reporting via email and logfile.
I'm using simplemonitor from github commit abbfb037c28f7f017bc82fc313b94e9ba4e069f8.

Let me know if I can provide some other information, test something, etc.

**Comment by cpina** [comment]
Now testing with commit efe20a851ff06abd1081a8bdaf05632542529cad .

**Comment by jamesoff** [comment]
Thanks for the report and testing. I'll take a look, but I've not had SimpleMonitor run other hosts out of memory (knowingly), so I've not done much in the way of investigating Python memory usage. What version of Python are you using?

**Comment by cpina** [comment]
Using Python 3.5.3 (default in Debian Stretch).

**Comment by cpina** [comment]
Every 24h it uses 10 MB more:
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
carles    8128  8.8  2.7  80308 28128 pts/3    S+   22:52   0:01 python3 monitor.py
carles    8128  5.2  3.0  91072 30676 pts/3    S+   Jul22  76:37 python3 monitor.py
carles    8128  5.7  3.9 102304 40112 pts/3    S+   Jul22 167:32 python3 monitor.py

**Comment by jamesoff** [comment]
Interesting, not sure I’ve seen other instances do that.

Can you share your config? You can email it directly to me if you don’t
want to post it here, and you can anonymise things if you like.

-- 
James Seward

**Comment by cpina** [comment]
I've sent the configuration via email. If not received let me know.

**Comment by jamesoff** [comment]
Just to let you know I've not forgotten this, but I've been busy!

If you're feeling brave, there's a commit on `feature/memory` you could try (not the WIP one, the first one) which may improve things.

**Comment by cpina** [comment]
I'll test now, thanks!

**Comment by cpina** [comment]
I think that this bug is fixed as expected. My current simplemonitor process started on 28th October and the memory doesn't seem to increase.

**Comment by jamesoff** [comment]
Great, I'll merge that in. Thanks for letting me know :)

**Comment by cpina** [comment]
I think that I'm still having this problem. Or having it again.

I'll send by email the configuration, but I have this script:

LOG_FILE="/home/carles/.simple-monitor-monitor.log"

    date >> "$LOG_FILE"
    ps auxw | grep -i "python3 monitor.py" | grep -v grep | grep -v SCREEN | grep -v "bash" >> /home/carles/.simple-monitor-monitor.log

The output:
for 5 days (I just copy-paste the first and the last lines):
Mon Apr  1 23:24:01 CEST 2019
carles    1853  4.5  3.5 102864 36036 pts/0    S+   22:55   1:17 python3 monitor.py
Tue Apr  2 00:24:01 CEST 2019
carles    1853  4.6  3.7 104356 37620 pts/0    S+   Apr01   4:05 python3 monitor.py
Tue Apr  2 01:24:01 CEST 2019
carles    1853  4.8  3.8 105948 39140 pts/0    S+   Apr01   7:07 python3 monitor.py
Tue Apr  2 02:24:01 CEST 2019
carles    1853  4.9  4.0 107420 40588 pts/0    S+   Apr01  10:15 python3 monitor.py
Tue Apr  2 03:24:01 CEST 2019
carles    1853  5.0  3.8 109020 38812 pts/0    S+   Apr01  13:28 python3 monitor.py
Tue Apr  2 04:24:02 CEST 2019
carles    1853  5.1  3.9 110512 40384 pts/0    S+   Apr01  16:45 python3 monitor.py
Tue Apr  2 05:24:01 CEST 2019
carles    1853  5.1  4.1 111972 41884 pts/0    S+   Apr01  20:06 python3 monitor.py
Tue Apr  2 06:24:01 CEST 2019
carles    1853  5.2  4.3 113560 43620 pts/0    S+   Apr01  23:29 python3 monitor.py
Tue Apr  2 07:24:01 CEST 2019
carles    1853  5.3  4.4 115036 45128 pts/0    S+   Apr01  26:58 python3 monitor.py
Tue Apr  2 08:24:01 CEST 2019
carles    1853  5.3  4.6 116500 46608 pts/0    S+   Apr01  30:28 python3 monitor.py
...
carles    1853  7.2  7.9 222156 80172 pts/0    S+   Apr01 355:07 python3 monitor.py
Fri Apr  5 09:24:01 CEST 2019
carles    1853  7.2  8.0 223752 81356 pts/0    S+   Apr01 360:11 python3 monitor.py
Fri Apr  5 10:24:01 CEST 2019
carles    1853  7.2  8.1 225092 82424 pts/0    S+   Apr01 365:14 python3 monitor.py
Fri Apr  5 11:24:01 CEST 2019
carles    1853  7.3  8.2 227220 83848 pts/0    S+   Apr01 370:16 python3 monitor.py
Fri Apr  5 12:24:01 CEST 2019
carles    1853  7.3  8.0 228024 81612 pts/0    S+   Apr01 375:20 python3 monitor.py
Fri Apr  5 13:24:01 CEST 2019
carles    1853  7.3  8.1 229364 83012 pts/0    R+   Apr01 380:28 python3 monitor.py
Fri Apr  5 14:24:01 CEST 2019
carles    1853  7.3  7.8 231228 79424 pts/0    S+   Apr01 385:30 python3 monitor.py
Fri Apr  5 15:24:01 CEST 2019
carles    1853  7.3  7.5 232300 76088 pts/0    S+   Apr01 390:30 python3 monitor.py

I don't usually monitor processes :-) is that when simplemonitor is running for weeks then I have memory usage consumption.
I'm using: 72554c28126f1f95e46c167c5c7c1c4b37891979 version.

**Comment by cpina** [comment]
And like before, my Python version is 3.5.3.

**Comment by jamesoff** [comment]
Ok, sorry to hear that.

Thanks for the configs by email. I'll have another go at getting to the bottom of this!

**Comment by cpina** [comment]
I'm using for quite a while a recent simplemonitor, with Python 3.9 and I haven't had any problem.
I suggest to close this issue :-)
