### ISSUE TITLE
Http failure delay

### ISSUE THREAD

**Issue by Rustymage** [jamesoff/simplemonitor#106]
Recently I've been alerted to failures of my webpage which I suspect is related to the monitor timing out. 

Is there a way of allowing for a longer http check, or am I being a noob?

The http page is one I run on a neighbouring raspberry pi on the same LAN. It can sometimes take 20 seconds or more to respond.

Any thoughts? 

Thanks.

:)

**Comment by jamesoff** [comment]
There's a `timeout` option you can specify for `http` monitors, but it wasn't in the docs. I've updated them; give it a go and let me know if it does what you need.

e.g.
`timeout=30`

**Comment by Rustymage** [comment]
Thanks, I’ve added that and it’s behaving 😀
