### ISSUE TITLE
Command Monitor

### ISSUE THREAD

**Issue by tlegras** [jamesoff/simplemonitor#11]
I think what is missing is a generic monitor that would allow to launch a preconfigured command (in monitors.ini) and check result using a regexp. This would allow to monitor virtually anything that is not offered by the list of monitor. This monitor could also check if the output is balow a max value (to monitor memory, disk, cpu ...)

Ex1: monitor if a some process is running
```
command="ps auxww | grep mysoftware"
result_regexp="mysoftware -myparam"

```
Ex2: if command is returning a value, test if the value is below a given value. In this example we count the number of postgres connection and we check it is below max connection 
```
[postgresql-connectionmax-monitor]
command="ps auxww | grep ^postgres | wc -l"
result_max=100

```

I have already coded such monitor, I can send you if interesting (not under git however, but this is just one file) + 2 lines in monitor.py

**Comment by jamesoff** [comment]
That would be useful, yes. If you can do it as a pull request on Github please do, but if not please send it to me some other way and I'll include it.

**Comment by tlegras** [comment]
let's try this way: attached command.py to place inside Monitors folder

also insert in monitor.py:

> import Monitors.command


and

>         elif type == 'command':
>             new_monitor = Monitors.command.MonitorCommand(monitor,
> config_options)


configuration examples:

[pgsql-connections-max]
type=command
command="ps auxww | grep ^postgres | wc -l"
result_max=190

[pgsql-postmaster-alive]
command="ps -auxww | grep ^postgres"
result_regexp=postmaster

and that's all :)


2016-04-20 19:13 GMT+02:00 James Seward <notifications@github.com>:

> That would be useful, yes. If you can do it as a pull request on Github
> please do, but if not please send it to me some other way and I'll include
> it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jamesoff/simplemonitor/issues/11#issuecomment-212519159>
>



-- 
Thierry.


"""Command output monitor for SimpleMonitor."""

import urllib2
import re
import subprocess
import socket
import datetime
import subprocess

from monitor import Monitor


class MonitorCommand(Monitor):
    """Check the output of a command.

    We can check for a regexp match in the ouput or give a max value and check the output is lower that this value.
    """

    command = ""
    result_regexp = None
    result_regexp_text = ""
    result_max = None

    type = "command"

    def __init__(self, name, config_options):
        Monitor.__init__(self, name, config_options)

        self.result_regexp_text = ""
        self.result_regexp = None
        self.result_max = None
        
        if 'result_regexp' in config_options:
            self.result_regexp_text = config_options["result_regexp"]
            self.result_regexp = re.compile(self.result_regexp_text)
        elif 'result_max' in config_options:
            self.result_max = int(config_options["result_max"])
        else:
            raise RuntimeError("Required configuration fields missing")

        try:
            command = config_options["command"]
        except:
            raise RuntimeError("Required configuration fields missing")
        if command == "":
            raise RuntimeError("missing command")
        self.command = command

    def run_test(self):
        success = False
        try:
            out = subprocess.check_output(self.command)
            # print(out)
            if self.result_regexp != None:
                matches = self.result_regexp.search(out)
                if matches:
                    self.record_success()
                    return True
            elif self.result_max != None:
                # print(out)
                outasinteger=int(out)
                if outasinteger < self.result_max:
                    self.record_success("%s < %s" % (outasinteger, self.result_max))
                    return True
                else :
                    self.record_fail("%s >= %s" % (outasinteger, self.result_max))
                    return True
        except Exception, e:
            self.record_fail(e)
            return False
            
        self.record_fail()
        return False

    def describe(self):
        """Explains what this instance is checking"""
        return "checking a command %s match a regexp %s" % (self.command, self.result_regexp_text)

    def get_params(self):
        return (self.command, self.result_regexp_text)

**Comment by tlegras** [comment]
here is monitor.py:

note that I used subprocess.Popen since os.popen is deprecated and does not seem to support complexe parameter list with double quotes inside.

```

"""Command output monitor for SimpleMonitor."""

import urllib2
import re
import subprocess
import socket
import datetime
import subprocess

from monitor import Monitor


class MonitorCommand(Monitor):
    """Check the output of a command.

    We can check for a regexp match in the ouput or give a max value and check the output is lower that this value.
    """

    command = ""
    result_regexp = None
    result_regexp_text = ""
    result_max = None

    type = "command"

    def __init__(self, name, config_options):
        Monitor.__init__(self, name, config_options)

        self.result_regexp_text = ""
        self.result_regexp = None
        self.result_max = None
        
        if 'result_regexp' in config_options:
            self.result_regexp_text = config_options["result_regexp"]
            self.result_regexp = re.compile(self.result_regexp_text)
        elif 'result_max' in config_options:
            self.result_max = int(config_options["result_max"])
        else:
            raise RuntimeError("Required configuration fields missing")

        try:
            command = config_options["command"]
        except:
            raise RuntimeError("Required configuration fields missing")
        if command == "":
            raise RuntimeError("missing command")
        self.command = command

    def run_test(self):
        success = False
        try:
            out = subprocess.check_output(self.command)
            # print(out)
            if self.result_regexp != None:
                matches = self.result_regexp.search(out)
                if matches:
                    self.record_success()
                    return True
            elif self.result_max != None:
                # print(out)
                outasinteger=int(out)
                if outasinteger < self.result_max:
                    self.record_success("%s < %s" % (outasinteger, self.result_max))
                    return True
                else :
                    self.record_fail("%s >= %s" % (outasinteger, self.result_max))
                    return True
        except Exception, e:
            self.record_fail(e)
            return False
            
        self.record_fail()
        return False

    def describe(self):
        """Explains what this instance is checking"""
        return "checking a command %s match a regexp %s" % (self.command, self.result_regexp_text)

    def get_params(self):
        return (self.command, self.result_regexp_text)

```

**Comment by jamesoff** [comment]
See #15
