### ISSUE TITLE
ping command is wrong for non-windows systems

### ISSUE THREAD

**Issue by bmusat** [jamesoff/simplemonitor#12]
For windows you are doing a "ping -n 1 -w 5000 %2" which sends 1 ping with a timeout of 5000ms or 5 seconds.

If it is not a windows system it basically uses "ping -c1 -t5 %s" which sets the TTL to 5, which is NOT the same as timeout.  "-t" is the number of hops.   I think you probably mean to use -w5 or -W5.

**Comment by jamesoff** [comment]
Interesting, look like this isn't even consistent across UNIXy systems either - on OS X `-t` is timeout (ping exits after this long), `-W` is wait time (ping waits this long for a reply) and `-T` is TTL.

On a Debian machine, it matches your report - `-t` is TTL and `-W` is the wait time (`-w` is the equivalent to `-t` on OS X).

Sadly the POSIX standard is non-free :/ Looks like `-W` is the most portable though.

**Comment by jamesoff** [comment]
@bmusat Have a look at PR #13
