### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by tompayne36** [jamesoff/simplemonitor#1222]
I have been a happy SimpleMonitor user for some time now. Unfortunately, when I recently rebooted my Raspberry Pi Zero is was running on, the machine would not reboot...so I have been reinstalling everything. When I run "pip install simplemonitor", I seem to be having some compatibility issues with "cryptography". It seems to want me to install Rust. I have tried various options to fix this, including installing an earlier, non-Rust version (pip install cryptography==3.3.2). While the simplemonitor install completes, now when I run the program, I get "illegal instruction". Would appreciate any ideas/guidance.

I am running 32-bit OS on Raspberry Pi Zero (armv61) - Python 3.9.2

**Comment by jamesoff** [comment]
With apologies for the delayed response :)

Can you check your Python install on the Pi is set up to use "piwheels", which is a Python package repo which holds pre-built binary packages for Raspberry Pi - they have instructions on https://www.piwheels.org/

That should hopefully let you get a pre-built crypotography wheel without the need to install Rust to build it yourself.

**Comment by jamesoff** [comment]
Closing, please reopen with more detail if you're still having problems.
