### ISSUE TITLE
`logfile` and `logfileeng` output: specify the directory

### ISSUE THREAD

**Issue by cpina** [jamesoff/simplemonitor#1333]
For what I can see: the `logfile` / `logfileeng` alerters have `filename` and this needs to be the filename and not the file path. I'd like to be able to specify a file path to be able to launch simplemonitor from any directory instead of having to run it from the directory where the output is going to be generated.

If this is already possible: apologies, please let me know :-)

**Comment by jamesoff** [comment]
Just checked and both definitely support full path/filenames in `filename` :)

**Comment by cpina** [comment]
> Just checked and both definitely support full path/filenames in filename :)

I took the documentation saying "filename" too literal (I thought that it meant "file path cannot be there") (e.g. https://simplemonitor.readthedocs.io/en/latest/loggers/logfileng.html?highlight=fileng#confval-filename). I might have tested that day and failed for another reason...

All good (or feel free to add an example in the documentation with the full path :-) )
