### ISSUE TITLE
Specify `monitor.ini` and `monitors.ini` directory

### ISSUE THREAD

**Issue by cpina** [jamesoff/simplemonitor#1334]
In order to have the `monitor.ini` and `monitors.ini` in a specified directory I need to:

 * Run simplemonitor with `--config /etc/simplemonitor/monitor.ini`
 * In `/etc/simplemonitor/monitor.ini` have `monitors = /etc/simplemonitor/monitors.ini` line

It would be more natural for me to do something such as:

* Run simplemonitor with `--config-dir /etc/simplemonitor` and then avoid the full path in `monitors`

I need the full path there because I need to run simplemonitor from `/var/log/simplemonitor` in order to have the logs outputted in `/var/log/simplemonitor`

**Comment by jamesoff** [comment]
Just having a look at this and pondering. Which logs do you mean? Like the "file" logger? You can specify a fully qualified filename for that, if it helps.

**Comment by cpina** [comment]
> Just having a look at this and pondering. Which logs do you mean? Like the "file" logger? You can specify a fully qualified filename for that, if it helps.

I cannot remember if I tested and didn't work; or I didn't test it because I assumed that "filename" is a file name not a file path :-/

I meant that in `monitor.ini` I have:
```
[logfile]
type=logfileng
filename=simplemonitor.log
only_failures=1
```

https://simplemonitor.readthedocs.io/en/latest/loggers/logfileng.html#confval-filename

I'm pretty sure that I thought that "filename" is only the file name, not the file path :-/

In all my deployments of simplemonitor I log in the simplemonitor cwd (because how I do the deployment this makes sense).

I'll test it and I'll make some changes in the Debian package so it does not need to change the current working directory before running simplemonitor.

Feel free to close this issue (or add a comment in the docs if it's suitable), I would re-open it if I find a problem.

**Comment by jamesoff** [comment]
Pretty sure it should take a fully path/filename - it just passes the value to Python's `open()` :)

If that works for you then I think that's the neater solution, else I have to change the directory back and forth when reading config files, or make sure to prefix with the "config dir" value whenever I use them - neither of which are impossible, but don't "feel" right.

Definitely re-open if you can't make it work the way you need though.

**Comment by cpina** [comment]
(I don't think that I can re-open a closed issue)

I am improving the Debian package and found what I had meant when I opened the issue.

First of all: discard (forget) this part of my original message

> I need the full path there because I need to run simplemonitor from /var/log/simplemonitor in order to have the logs outputted in /var/log/simplemonitor

Since `logfile` / `logfileng` loggers accept, as a filename, a full path: I don't need to run simplemonitor from a specific directory :+1: 

I am running `simplemonitor` via: `/usr/bin/python3 /usr/bin/simplemonitor --config /etc/simplemonitor/monitor.ini`. In `/etc/simplemonitor/monitor.ini` I need the full path for the monitors: `monitors=/etc/simplemonitor/monitors.ini`.

It seems redundant to have the full path twice.

The docs in https://simplemonitor.readthedocs.io/en/latest/configuration.html#confval-monitors say `Relative to the cwd, not the path of this configuration file.` . My suggestion was `relative to --config-dir` (in my case, it would be relative to `/etc/simplemonitor`.

So, instead of passing the full path to `monitor.ini` and this one the full path to `monitors.ini`: my issue was to suggest a new argument `--config-dir` and find `monitor.ini`  and `monitors.ini` there.

**Comment by cpina** [comment]
It works for me, thanks for asking.
