### ISSUE TITLE
monitor.ini email alerter: from can be of form `Something <user@example.org>`

### ISSUE THREAD

**Issue by cpina** [jamesoff/simplemonitor#1338]
The docs say:

https://simplemonitor.readthedocs.io/en/latest/alerters/email.html
```
the email address to give as the sender
```

But it's possible to have:
```
from=Server XXX <noreply@example.org>
```

The use case is that I have one SMTP account to send alerts from different servers. So I can identify the server easier on some email clients.

I don't know whether this is an "accident" that works (code does not enforce neither deny) or if it could be documented.

For years, I had only the "email" because I followed the docs to the letter.

**Comment by jamesoff** [comment]
I guess smtplib or whatever it is I'm using (it's been a while) just passes that value in to the headers of the mail/envelope, so it makes sense it can work. I'd never thought to try it :D

I'll update the docs to include it.
