### ISSUE TITLE
Reporting to "HTML" without map_start: does not load page

### ISSUE THREAD

**Issue by cpina** [jamesoff/simplemonitor#1344]
The documentation says (https://simplemonitor.readthedocs.io/en/latest/loggers/html.html?highlight=html#confval-map_start):
> map_start
>
>    Type        comma-separated list of float
>    Required        false

Simplemonitor loads without map_start (`simplemonitor --test` does not return an error) but the generated HTML page does not load.

The HTML looks like:
```
      <script>
        var mymap = L.map('mapid', {
          center: [, ],
          zoom: 
        });
```

Firefox dev console says:
> Uncaught SyntaxError: expected expression, got '}'

Writing the map_start lat, long and zoom works correctly.

**Comment by jamesoff** [comment]
I'll make `map_start` required.
