### ISSUE TITLE
Reporter HTML: consider moving away from mapbox.com?

### ISSUE THREAD

**Issue by cpina** [jamesoff/simplemonitor#1345]
When setting up the html reporter with a map it's needed a mapbox API key. To get the API key from mapbox it's needed to create an account, verify the email, add a debit/credit card (!).

I create similar (same?) maps via (this is from a hobby, unreleased project):
```
	var map = L.map('mapid').setView([41.38, 2.16], 16);


	L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
		maxZoom: 18,
		attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, ' +
			'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
		id: 'mapbox/streets-v11',
		tileSize: 512,
		zoomOffset: -1
	}).addTo(map);
```
Which does not need an API key. For what I remember, when I did it a few years ago, it was documented via Leaflet or OSM to use their tiles for fair use?

PS: probably the attribution is not correct in my example above, see #1346

**Comment by jamesoff** [comment]
Ah interesting, and good idea. I don't use this feature in SimpleMonitor myself but I do use Leaflet+OSM in another project. I'll update SimpleMonitor to be OSM.

**Comment by jamesoff** [comment]
I've updated it to be pure OSM and modified the attribution accordingly, to a format their page deems acceptable :)

I also made it output a note about the mapbox token no longer being needed, if one is present in the configuration.
