### ISSUE TITLE
Monitoring untrusted hosts

### ISSUE THREAD

**Issue by ProgVal** [jamesoff/simplemonitor#143]
Hi,

I'm considering using simplemonitor for my servers. I noticed it uses pickle to transfer data from a client to the master host, so a malicious/compromised client could run arbitrary code on the master.
How hard would it be to replace pickle with a safe protocol, like JSON or XML?

Thanks!

**Comment by jamesoff** [comment]
Hi,

As it stands, that would be moderately non-trivial but not impossible.

However, since 1.6 (actually, since c88f11c), SimpleMonitor uses a shared secret to validate the pickled data that's arrived to mitigate this issue. Hopefully that's safe enough for you? (And I'm by no means a crypto expert so if you know of an issue with that implementation please let me know!)

Thanks :)

**Comment by ProgVal** [comment]
Thanks for the quick reply!

Unfortunately, a shared secret does not protect from a compromised host, because the attacker would have access to the secret :/

**Comment by jamesoff** [comment]
Indeed, although as you say they then already have access to at least one of your hosts and there may well be other options for lateral movement in the network at that point.

Changing the network monitoring to use something like JSON (I'd always pick that over XML ;) is something I'd like to do but do not currently have the bandwidth for.

At the moment, pickle is used to instantiate Monitor instances on the receiving ends which allows them to be fully populated and easy to call methods on. (It seemed like a good idea at the time, which was ~2006!) Replacing that method with sending properties by JSON and creating/populating Monitor instances on the receiving end would probably suffice and let the rest of the code stay the same.

I'll have a think, but in the meanwhile if you happen to feel like trying your hand at it, I'm happy to receive pull requests.

**Comment by ProgVal** [comment]
> I'll have a think, but in the meanwhile if you happen to feel like trying your hand at it, I'm happy to receive pull requests.

Sure! 

I started some work here, feel free to take a look: https://github.com/jamesoff/simplemonitor/compare/master...ProgVal:remove-pickle

**Comment by jamesoff** [comment]
Looks like a good start :)

**Comment by jamesoff** [comment]
Happy to close this now?

**Comment by ProgVal** [comment]
Sure, thanks!
