### ISSUE TITLE
Failure to get ping data when using linux server

### ISSUE THREAD

**Issue by hmbl4** [jamesoff/simplemonitor#192]
I can see when any remote monitor fails, but, I am hosting monitor status from `html` folder structure and unable to see any ping data under the `detail` column as per the screenshot
Linux server with issue:
![screen shot 2018-12-11 at 2 13 04 pm](https://user-images.githubusercontent.com/29220320/49771640-ec633080-fd4e-11e8-9de7-be51c71992a1.png)

**Comment by hmbl4** [comment]
Turned out to be an issue with python version I was on

**Comment by jamesoff** [comment]
Anything I need to worry about, compatibility-wise? :)

**Comment by hmbl4** [comment]
No, just that running `python monitor.py` and `python3 monitor.py` tended to be the difference between the ping data rendering and not rendering.

**Comment by jamesoff** [comment]
Oh, I'd like Python 2 to work really (for now at least). I'll take a look.

**Comment by jamesoff** [comment]
Closing this as Python 2 support has been dropped.
