### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jamesoff** [jamesoff/simplemonitor#20]
No idea how compatible with Python 3 this is, but it would be nice it it worked.

**Comment by Cabalist** [comment]
Any interest in me porting the code to run on Python 3 as well? Is there a preferred way to do that? I see a branch for Python3 but it looks like it is just a travis.yml change.

Should I wait for the subprocess branch to merge?

(Closed new issue and appended to the existing one)

**Comment by Cabalist** [comment]
I just synced the Python3 to master and then applied the update.  This now runs on my machine but I am by no means using all the features.  Check out pull request #45

**Comment by jamesoff** [comment]
Yeah, I got as far as enabling the tests for it but not much further. I've no idea if there's a preferred way to do it, I've not used Python 3 much.

I should probably finish off the subprocess changes (I have them as a milestone for 1.7, and Python3 for 1.8).

Thanks very much for the PR, I'll take a look :)

**Comment by Cabalist** [comment]
This code should work for Python2 and Python3 I am not using any specific features of one or the other.  

Python 3 is great.  I'm really glad adoption has finally caught up.  

I have a handful of bug fixes and cleanup as well but feel like I should wait until it isn't competing with other branches.  :)

**Comment by jamesoff** [comment]
Cool :)

By all means feel free to generate PRs for the other things too if you like, always happy to receive contributions.

**Comment by Harkishen-Singh** [comment]
Running `python3 monitor.py` shows several syntax errors in many files. 
I will be really **happy** if I would be successful in converting the code to work in Python3.
Thanks.!
@jamesoff  can i do it?

**Comment by jamesoff** [comment]
@Harkishen-Singh check out the feature/python3 branch :) not finished yet, but I think the majority of it works (I'm also trying to get a bunch of testing written/working for it)

I think maybe the networking stuff needs some attention still (having one instance report to another), I haven't looked at that yet.

PRs against the python3 branch are welcome!

**Comment by Harkishen-Singh** [comment]
@jamesoff  , sure, i will look into the **network.py** and related stuff and try to make it compatible for python3. 
Thanks.!

**Comment by cpina** [comment]
+1 for Python3 :-) Thanks for all the good work!

**Comment by jamesoff** [comment]
Python 3 support is now merged to master and should 🤞 be working correctly. If you find any problems, please open a new issue for it.

**Comment by cpina** [comment]
Just to say thanks and that I've upgraded mine and at the moment all good!
