### ISSUE TITLE
monitors.ini (with an "s") is loaded on startup, documentation mentions monitor.ini

### ISSUE THREAD

**Issue by wsw70** [jamesoff/simplemonitor#215]
The [documentation ](http://jamesoff.github.io/simplemonitor/configuration.html)mentions that 

> The main configuration lives in monitor.ini in the same directory as the code.

When `monitor.ini` is

```
[monitor]
interval=60
```
the startup fails:

```
> python monitor.py
2019-01-18 13:06:32 CRITICAL (simplemonitor) Missing [monitor] section from config file, or missing the "interval" setting in it
```

I believe that this (also) means that the configuration file is not present.

When renaming `monitor.ini` to `monitors.ini` the startup is successful (at least the file is read in, other problems are in a separate issue)

EDIT: this is on the latest version as of the issue date (commit https://github.com/jamesoff/simplemonitor/commit/cb72a17bc456944efca3a95a457e59d78483f059)

**Comment by jamesoff** [comment]
Part documentation, part bad error message :)

To be clear, you should have a `monitor.ini` and a `monitors.ini`. You can blame 2008 me for that awful decision!

I'll revisit the possible ways to break it and make sure the errors reported are right/useful.

**Comment by jamesoff** [comment]
Glad it's useful for you. That's exactly why I started writing it; I too was fed up with Nagios, Zabbix and OpenNMS for what I needed at the time.

For the docs, if you `git checkout gh-pages` you'll switch to the documentation, and you can branch/PR off that.

**Comment by wsw70** [comment]
Thank you. I will make the proposal changes as I continue configuring (not
many, just some points which were not clear to me) and send a PR.

Le jeu. 24 janv. 2019 à 12:32, James Seward <notifications@github.com> a
écrit :

**Comment by wsw70** [comment]
> For the docs, if you `git checkout gh-pages` you'll switch to the documentation, and you can branch/PR off that.

@jamesoff I cannot find this branch, is it still in there?

![image](https://user-images.githubusercontent.com/1345886/52903106-7d57fb80-3219-11e9-98a1-855b348876f8.png)

**Comment by jamesoff** [comment]
Oops, I was tidying up because Github added support for docs being in `docs/` on the master branch, which solved an annoyance of mine (that the docs and code commits didn't relate to each other), so the docs are now in the main repo under that path.

If you're happy enough fixing the merge yourself that's where they are, else point me at your branch with your changes and I'll sort it out! Sorry about that.

**Comment by wsw70** [comment]
OK thanks. If you would be interested / considering using the GitHub Wiki
for the documentation I could poort it over there to further simplify the
management. This is really just a raised hand in case that would be the
case - you have a nice site with the docs and that's super but if this
would be something you would be looking at in the future I will be glad to
help.

Le lun. 18 févr. 2019 à 10:10, James Seward <notifications@github.com> a
écrit :

**Comment by jasonmadigan** [comment]
Bit related, which file does the `  -f CONFIG, --config CONFIG configuration file` refer to? Can I configure both paths somehow, or is one inherited from the other (e.g. pass one, and it'll look for the other in the same folder)? I'm a bit confused.
