### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by wsw70** [jamesoff/simplemonitor#228]
I will try to write a MQTT logger (based on the JSON logger) and before diving in wanted to check how strong / much required is Python 2 compatibility?

I only use Python 3 and would probably have a hard time making sure it is Python 2 backwards compatible. I could ensure, however, than the module would load only on a Python 3 installation - but I am not sure how much that would be OK for @jamesoff

**Comment by jamesoff** [comment]
I'm happy for it to only load on Python 3; if it could emit an error if something tries to use it on Python 2 telling them why that would be great.

**Comment by wsw70** [comment]
OK, noted. Thanks.
