### ISSUE TITLE
Cannot start listener: OSError: [Errno 97] Address family not supported by protocol

### ISSUE THREAD

**Issue by wsw70** [jamesoff/simplemonitor#232]
I wanted to set up remote data sending (that part works so far) and reception (this one does not). On the receiving side, I configured `simplemonitor` with

```
[monitor]
interval=60
remote=1
remote_port=9001
key=mysupersecretkey
```

When starting `simplemonitor`, I get 

```
2019-02-05 17:02:21     INFO (simplemonitor) Starting remote listener thread (allowing pickle data)
Traceback (most recent call last):
  File "/opt/simplemonitor/monitor.py", line 403, in <module>
    main()
  File "/opt/simplemonitor/monitor.py", line 310, in main
    m, remote_port, key, allow_pickle=allow_pickle)
  File "/opt/simplemonitor/Loggers/network.py", line 115, in __init__
    self.sock = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
  File "/usr/lib/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
```

There are references in the Traceback to `socket.AF_INET6`, which suggests some expectation towards IPV6. My server is IPV4 only.

**Comment by jamesoff** [comment]
Yeah looks like it’s from the IPv6 support recently. Maybe not catching the right exception if it’s not available… can’t look right now as I’m on my phone but will investigate.

**Comment by wsw70** [comment]
Created PR https://github.com/jamesoff/simplemonitor/pull/237
