### ISSUE TITLE
Over-enthusiastic splitting breaks MonitorCommand on Windows

### ISSUE THREAD

**Issue by jamesoff** [jamesoff/simplemonitor#25]
As per #15, the correct solution to this is to build the list of arguments separately to the command name, so I guess the command will need to be a separate parameter in the config

**Comment by tlegras** [comment]
note that there can be also whitespaces in some parameters with double quotes such as:
"C:\Program Files (x86)\Putty\plink.exe" -ssh 1.2.3.4 -l john "sudo service food status"

Maybe that split can be simply replaced by shlex.split?
