### ISSUE TITLE
The DNS monitor doesn't work consistently when a query returns multiple results

### ISSUE THREAD

**Issue by pycarus** [jamesoff/simplemonitor#252]
Hello,

MX and NS queries typically return multiple results, but those results are not necessarily returned in a specific order. When the order is different from the one listed in the config file, the monitor fails. 

The if statement should be:

if self.desired_val and set(result.split('\n')) != set(self.desired_val.split('\n')):

https://github.com/jamesoff/simplemonitor/blob/ac9e60380ddb11bad10e4936e6c12e7d07373cb3/Monitors/network.py#L293

**Comment by jamesoff** [comment]
Thanks! I created a test case for it too while I was at it :)

**Comment by wsw70** [comment]
Note to self: I really need to get off my laziness and learn how to write test cases in Python.

**Comment by jamesoff** [comment]
@wsw70 tbh I'm just kind of making it up as I go along; do not use this as any kind of best practice :D

**Comment by wsw70** [comment]
@jamesoff so you are already miles ahead of me. I am an amateur coder for 20 years and I am stewing in my own guilt, in addition of having a good friend who is a real software architect and who looks with pity when I code without test cases (Test Driven Development is one of his mottos)
