### ISSUE TITLE
hierarchical tree organisation in HTMLLogger

### ISSUE THREAD

**Issue by tlegras** [jamesoff/simplemonitor#26]
Improvement: I am working on a modified version of HTMLLogger where monitors are organised in a tree (using CompoungMonitor). The idea is to expand/collapse top level CompoungMonitor. if interested I could propose a pull request once I have tested it for some time. Changes are mainly in the javascript, and  a bit in HTMLLogger. State of the tree is preserved even when page reloads each minute :)

**Comment by jamesoff** [comment]
Sounds good, I'd love to see it :)

**Comment by tlegras** [comment]
here is what it looks like so far:

![clipboard01](https://cloud.githubusercontent.com/assets/949679/15118606/3c3c99ce-160d-11e6-9cff-4d600d1a298c.png)
![clipboard02](https://cloud.githubusercontent.com/assets/949679/15118610/40549f20-160d-11e6-8de9-2f967aa315e8.png)

**Comment by tlegras** [comment]
Good news: I have reworked my code based on this javascript with http://maxazan.github.io/jquery-treegrid/ which integrates much more smoothly with the simplemonitor :)
On Chrome and Firefox it works perfectly, the only issue is that the state of the tree is not persistant with internet explorer (e.g. tree restore to a fully expanded state each time the page reloads). However this would work in all browsers if the page is published using a web server. in any case the tree feature can be disabled easily by removing the javascript call in header.htm. 

The tree will add one constraint to the monitor naming: leaves name must be following their parent in alphabetic order. So the typical naming should be "parentmonitor" "parentmonitor/level1leaf" "parentmonitor/level1leaf/level2leaf" to ensure that. in the html page in monitor column everything that is before last "/" is removed so that names are not too long

I will continue to test it for a moment and will then propose a pull request

**Comment by mikebro19** [comment]
The would be a very welcome enhancement. Is there any chance that it might be incorporated?

**Comment by jamesoff** [comment]
@mikebro19 A PR never materialised, and the HTML page got a bit of a rework recently (not to add any kind of tree organisation, but the look got changed a bunch) so I don't know how easy @tlegras work would be to apply to it now. However, it is a feature I'd like to have (along with other things such as making the table sortable and filterable etc).
