### ISSUE TITLE
support for SSL certificate client authentication with HTTPMonitor

### ISSUE THREAD

**Issue by tlegras** [jamesoff/simplemonitor#27]
Hi, 
Today I needed to add support for client authentication in HTTPMonitor. I did the modifications with a local copy of git repo (basic support, password protected keyfile are not supported). I am ready to deliver it if interested... 
If so... just note that I am a begginer with github :)
I tried to take a look at pull request button: it seems a branch must be created before? I have worked in a branch locally on my workstation, is there some kind of sync to propagate the branch creatin on github? or is it the owner of the project who is doing that? 
(i am using gitgui, not github desktop)

**Comment by jamesoff** [comment]
I am interested, yes :)

A PR would be great, and I think the easiest way to do it is this:

* Hit the Fork button top right on Github to get your own copy of my repo
* Clone this new repo to your computer (in a different directory to your current one)
* Create a new branch in this new repo (Gitgui should be able to do that for you); you can call it whatever you like but something like "ssl-client-auth" seems appropriate
* Copy your changes from your original repo to this new one
* add/commit the changes
* Push this new branch (with your changes) up to github
* On github, create the pull request - if you go to your repo's page (and maybe refresh) it should add a button for making a PR for your new branch
* I merge the changes into my repo :)

(There's other more clever ways to do this, but this is probably the most straightforward if you're not too familiar with git)

Possibly useful references:
* https://help.github.com/articles/fork-a-repo/
* https://help.github.com/articles/using-pull-requests/

**Comment by tlegras** [comment]
Done. Thx so much for the tuto!! :) i am experienced in version control but not at all to git/github

Note: the code uses httplib.HTTPSConnection https://docs.python.org/2/library/httplib.html  which is deprecated. https://docs.python.org/2/library/ssl.html#ssl.SSLContext.load_cert_chain should be used instead (it seems to support for password encryption of keyfile) but it is only for python 2.7.9 and lated.

**Comment by jamesoff** [comment]
Glad my instructions made sense, and thanks for the code :)

I have #24 open to replace urllib2 with the requests library, so hopefully that will make the code a little nicer!
