### ISSUE TITLE
Add DB support for monitors

### ISSUE THREAD

**Issue by alimovz** [jamesoff/simplemonitor#329]
Currently when a new monitor is added to monitors.ini, I need to restart the monitor.py script. Or, for that matter, any changes made to _monitor.ini_ require a restart. Is there a way to database the monitors so that additions of new monitors is dynamically processed by monitor.py?

**Comment by jamesoff** [comment]
I'm afraid there isn't a way to do it at the moment, but it's something I'd like to support.

**Comment by jamesoff** [comment]
Released in 1.9.
