### ISSUE TITLE
Update monitors without restart

### ISSUE THREAD

**Issue by mikebro19** [jamesoff/simplemonitor#345]
Is there a way to update the list of monitors without restarting. The issue is that if there are devices offline and you restart, the system will generate new alerts. Since the alerts are generating helpdesk tickets, we get duplicate tickets.

Alternatively, a change that does not generate alerts if the device is offline at startup - perhaps a startup command line argument?

**Comment by jamesoff** [comment]
I'm afraid not, but it's on my wishlist :)

**Comment by jamesoff** [comment]
(Related to #329)

**Comment by jamesoff** [comment]
@mikebro19 If you're interested in testing, have a look at the feature/dynamic-reload branch. Send it SIGHUP to make it reload the config. At the moment, it only reloads monitors/alerters/loggers (and the value of `interval`; other changes in the main config won't take effect).

**Comment by mikebro19** [comment]
James

Unfortunately I am running on Windows which doesn't handle SIGHUP. :(
________________________________

**Comment by jamesoff** [comment]
Is there a method you'd expect to trigger a reload on Windows? Maybe I can implement that?

Failing that, maybe I can trigger a reload if the config files change on disk.

**Comment by mikebro19** [comment]
Have a look at https://github.com/nats-io/nats-server/issues/521

Checking the update on the file is dangerous as it could be in the process of being updated and a saved file could not be a fully valid config.  So for a file based trigger, you could monitor a 'trigger' file - so to trigger the update the user just 'touches' the file.
[https://repository-images.githubusercontent.com/6443435/3268ab80-6ff2-11e9-9999-35438a733a6a]<https://github.com/nats-io/nats-server/issues/521>
Strategy for signaling config reload on Windows · Issue #521 · nats-io/nats-server · GitHub<https://github.com/nats-io/nats-server/issues/521>
On Unix platforms, the plan is to expose config reload using SIGHUP. However, Windows doesn't have an equivalent and is limited to the interrupt signal. We need to determine a strategy for signaling config reloads on Windows. One option ...
github.com

________________________________

**Comment by jamesoff** [comment]
Yeah, I was thinking there would have to be caveats around moving the edited file into place rather than editing it in-situ. Having a trigger file was something I was pondering. I'll have a play with some code and see how it comes out.

**Comment by jamesoff** [comment]
Released in 1.9
