### ISSUE TITLE
Notification via external SMTP server with password ?

### ISSUE THREAD

**Issue by kovalroma** [jamesoff/simplemonitor#38]
Hello!

How can I configure this script to notify me with email using external SMTP server? 

I found this options
[email]
type=email
host=mailserver.domain.local
from=monitor@domain.local
to=administrator@domain.local

but my SMTP server requires login, password for sending email.

**Comment by jamesoff** [comment]
Currently not supported, but it doesn't look like too much work to add SMTP auth. I'll take a look :)

**Comment by jamesoff** [comment]
@kovalroma i've added `username` and `password` configuration options to the email alerter.

You can also specify `ssl=starttls` now, if your mail server supports that.

**Comment by kovalroma** [comment]
@jamesoff thank you! Are you going to merge this fix with master branch ?

**Comment by jamesoff** [comment]
This one is already merged. 

I'll merge the ssl one later (I'm away for a few days with limited internet)

**Comment by kovalroma** [comment]
Thank you for good job!

**Comment by nandoflorestan** [comment]
Hmmm, but the project documentation must be updated to mention these configuration options.

**Comment by jamesoff** [comment]
@nandoflorestan Done!

**Comment by nandoflorestan** [comment]
\o/  Thank you!
