### ISSUE TITLE
Installation Issue on Raspberry Pi

### ISSUE THREAD

**Issue by chriskacerguis** [jamesoff/simplemonitor#383]
Hello,

I just downloaded the latest code, and when running pip3 install -r requirements.txt I ran into the following error:

```
botocore 1.13.39 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.
```

```sh
root@raspberrypi:~/simplemonitor# python3 --version
Python 3.7.3
```

Any ideas on what I need to do to fix this?

PS thank you very much for writing and supporting this (I love simple monitor)

**Comment by cpina** [comment]
I'm just a regular simplemonitor user. To avoid problems with dependencies between system and requirements.txt dependencies you could use simplemonitor in a venv (virtual environment).

I've just done this in a server:
```
git clone git@github.com:jamesoff/simplemonitor.git
virtualenv venv -p python3
. venv/bin/activate
pip3 install -r requirements.txt 
```

Then in this shell try to use simplemonitor.

And remember that before using it to do:
```
cd simplemonitor # or the directory where you have it
. venv/bin/activate
```
Then launch simplemonitor (python3 simplemonitor.py)

Hopefully it helps!

**Comment by jamesoff** [comment]
Thanks @cpina! I do need to update the installation instructions to discuss using a venv, however I'm partway through making it so you can "pip install simplemonitor" so updating the instructions will be part of finishing that.

**Comment by jamesoff** [comment]
Done with 1.9. Hopefully the updated docs and the availability of the pip package address this for you!
