### ISSUE TITLE
Slack webhook payload configuration

### ISSUE THREAD

**Issue by jtrip** [jamesoff/simplemonitor#42]
I've used slack webhooks a bit and from what I understand it expects a post with some data with the message you want posted. However I am not seeing how I can configure that in the my slack alerter.

**Comment by jamesoff** [comment]
The message is generated by the alerter so you should get something like this screenshot. Did you want to add a custom message?

![screen shot 2016-09-23 at 09 34 44](https://cloud.githubusercontent.com/assets/5112771/18779460/0f8e749a-8171-11e6-9b80-ec36d1673cd2.png)

**Comment by jtrip** [comment]
Thanks, I was under the impression that I had to create the message to be sent, but I got it working. If I wanted to customize that where should I look?

**Comment by jamesoff** [comment]
If you're feeling like hacking, look here: https://github.com/jamesoff/simplemonitor/blob/master/Alerters/slack.py#L55 (and line 97 or so for the success message).

If you're not, let me know what you'd like to be able to do with it and I'll see what I can do for you.

**Comment by jamesoff** [comment]
Closing. Feel free to open a new issue if there's something specific you need adding.
