### ISSUE TITLE
windows pywin32 package is missing in the requirements.txt file

### ISSUE THREAD

**Issue by wurlog** [jamesoff/simplemonitor#423]
When using the DiskSpace monitor this error accourse 

```
raise RuntimeError("win32api is not available, but is needed for DiskSpace monitor.")
RuntimeError: win32api is not available, but is needed for DiskSpace monitor.
```
quick fix: use pip 

`pip install pywin32`

**Comment by jamesoff** [comment]
Thanks; it's included in the upcoming release which is pip-installable; I'm also adding it to Pipfile/requirements.txt.
