### ISSUE TITLE
Obtain and log public IP address

### ISSUE THREAD

**Issue by hattesen** [jamesoff/simplemonitor#47]
I have a situation, where an internet connection has an automatic failover to a 4G/SIM based connection, which takes about a minute to establish a connection, and will provide another public IP address, which may cause connection issues to certain services.

Therefore, I would like to monitor and log such a change of public IP address.

It would be nice to add an option that allows the public IP address to be obtained and logged.

This requires an external web service to be accessed, whose URL needs to be made a parameter.

To extract the public IP address from the service response, you could either simply use a regex to extract the first IPv4-formatted string in the response ('[0-9]{1,3}\.{3}[0-9]{1,3}'), or allow a regex parameter to be supplied.
Possible public ip address services:
- https://wtfismyip.com/text
- http://api.ipify.org/?format=txt
- http://whatismyip.org/ (HTML formatted response)

**Comment by jamesoff** [comment]
Or indeed https://api.jamesoff.net/reflect/v1 ;)

A monitor to watch the output of one of those services and log when it changes should be doable.

**Comment by jamesoff** [comment]
Going to pass on this, having revisited it doesn't really fit into the "monitor" paradigm (what counts as a pass or fail?)

You may be able to implement it directly using a `command` monitor and a shell script which `curl`s (or maybe better, uses httpie) one of the what's-my-ip endpoints and persists that in a file to compare between runs.

If you think it would work as a monitor please feel free to add comments with your thoughts :)
