### ISSUE TITLE
Twilio SMS

### ISSUE THREAD

**Issue by audiether** [jamesoff/simplemonitor#476]
Would be great to add Twilio as an alternate SMS service for alerting.

**Comment by jamesoff** [comment]
@audiether if still appropriate, would you be able to give the `feature/twilio` branch a spin to test it for me?

**Comment by audiether** [comment]
> @audiether if still appropriate, would you be able to give the `feature/twilio` branch a spin to test it for me?

@jamesoff I can try in about a week or so.  I won't have access until then.

**Comment by jamesoff** [comment]
@audiether Yup no problem :)
