### ISSUE TITLE
Slack alerter exception on missing channel

### ISSUE THREAD

**Issue by robcza** [jamesoff/simplemonitor#48]
Getting this exception while trying to make the Slack alerting working:
```exception caught while alerting for mymonitor: SlackAlerter instance has no attribute 'channel'```

The same exception is generated for this config (tried this one as the channel attribute is not mandatory)
```
[slackalert]
type=slack
url=https://hooks.slack.com/services/my/generated/webhook
```

but for this one as well:
```
[slackalert]
type=slack
url=https://hooks.slack.com/services/my/generated/webhook
channel=alerts
```

**Comment by robcza** [comment]
Oh well, the culprit was the requests requirement. Using ```pip install -r requirements.txt``` fixed everything, Slack alerting working now.

**Comment by jamesoff** [comment]
Glad you got it fixed, but it sounds like the code could be more helpful in reporting what might be broken.
