### ISSUE TITLE
typing.NoReturn not fully supported in Python 3.5 and 3.6

### ISSUE THREAD

**Issue by eht16** [jamesoff/simplemonitor#480]
`typing.NoReturn` was only added in 3.5.4 and 3.6.2 (https://docs.python.org/3/library/typing.html#typing.NoReturn).

On older patch releases of Python the code raises an ÌmportError`, obviously.
I suggest to not use `typing.NoReturn` or to make more clear that Python >= 3.5.4 or Python 3.6.2 is required.
It took me some time to figure this out on Debian Stretch which only has Python 3.5.3 :(.

Occurrences:
https://github.com/jamesoff/simplemonitor/blob/917a08a437bff687f8acf41a1aea3499fc40b34f/simplemonitor/Alerters/alerter.py#L9
https://github.com/jamesoff/simplemonitor/blob/917a08a437bff687f8acf41a1aea3499fc40b34f/simplemonitor/Monitors/monitor.py#L19

**Comment by jamesoff** [comment]
Apologies for wasting your time :( I had a battle with those versions too, before giving up on 3.5 (especially as it was holding the code back for other reasons too). The pip-installable version does now require >= 3.5, but not specifying >= 3.6.2 was an oversight.

Guessing you're using it straight from git, so I'll add the version requirements to the readme too; not having them there was a miss. Thanks for the feedback!
