### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Avshake** [jamesoff/simplemonitor#52]
`esoff-simplemonitor-9a863a6>python monitor.py
SimpleMonitor v1.7
--> Loading main config from monitor.ini
Traceback (most recent call last):
  File "monitor.py", line 413, in <module>
    main()
  File "monitor.py", line 284, in main
    interval = config.getint("monitor", "interval")
  File "C:\Python27\lib\ConfigParser.py", line 359,
    return self._get(section, int, option)
  File "C:\Python27\lib\ConfigParser.py", line 356,
    return conv(self.get(section, option))
  File "C:\Python27\lib\ConfigParser.py", line 607,
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'monitor'
`
**I get this error ever time i run monitor.py. I couldn`t figure our whats wrong. please provide solution as soon as possible.**

**Comment by jamesoff** [comment]
> ConfigParser.NoSectionError: No section: 'monitor'

What does your `monitor.ini` look like?

**Comment by Avshake** [comment]
**one of the monitor.ini file inside test goes like this...**
`[monitor]
monitors=tests/monitors.ini
interval=5

[reporting]
alerters=slack

[slack]
type=slack
url=https://hooks.slack.com/services/haha/nope/thisisjustatest
`
I have not changed any parameters in any file. I did according to the documentations with requirements yet it throws error.

**Comment by jamesoff** [comment]
That monitor.ini is a test one used for automated testing.

You need to create your own monitor.ini, in the same directory as monitor.py (or if in another location, use the `-f` option to tell monitor.py where it is) with your own configuration in it.
