### ISSUE TITLE
Timezones in Alerters

### ISSUE THREAD

**Issue by Eisfunke** [jamesoff/simplemonitor#527]
Since #489 loggers now have a option `tz` for specifying a timezone (thanks for that!). Alerters don't have one though. So, for example, I can't change (or haven't found out how to) the timezone of the `{failed_at}` variable in the `execute` alerter. Maybe adding a `tz` option for alerters just like the one for loggers would be nice.

**Comment by Eisfunke** [comment]
Thank you!

**Comment by jamesoff** [comment]
No problem :)
