### ISSUE TITLE
Loggers don't understand timezones?

### ISSUE THREAD

**Issue by jamesoff** [jamesoff/simplemonitor#53]
Reported by email; the logger.format_datetime() function and all the things it calls may ignore timezone info, and log in UTC.

**Comment by jamesoff** [comment]
Wow, local timezone stuff in Python is a mess; no wonder 2006 me just made everything UTC.

**Comment by wsw70** [comment]
As a side note, the nightmare with date manipulation vanished for me the day I started to use [`arrow`](https://arrow.readthedocs.io/en/latest/) instead of the Python built-in date zoo.

There are other contenders, such as [`delorean`](https://delorean.readthedocs.io/en/latest/) and another one which name escapes me right now.

**Comment by wsw70** [comment]
Whenever I have to use a date (even if it means getting it and displaying
the ISO version) I use arrow and it is so much, so much simpler. This is
really a life saver.
I moved a few programs from 2 to 3 and never witness any special issues
(but I started late in the game and the vast majority of what I coded was
in Python 3)

Le jeu. 24 janv. 2019 à 12:30, James Seward <notifications@github.com> a
écrit :

**Comment by b-lawlor** [comment]
Is there a work around for the timezone in the html logger?
The correct time shows up in the header and footer generated at... but UTC shows in the failed at column
UTC also shows in the text file log.

Can I hard code my timezone somehow?

**Comment by jamesoff** [comment]
@b-lawlor as a workaround, changing the uses of `utcnow()` to just `now()` in `record_fail` and `record_success` around here: https://github.com/jamesoff/simplemonitor/blob/master/Monitors/monitor.py#L265 should have the desired effect, although I've not tested it.

Fixing TZ stuff better is on my todo list, now I'm dropping Py2 support.

**Comment by b-lawlor** [comment]
Thanks @jamesoff ! I just set up this yesterday and it's perfect for my needs. You're awesome.

**Comment by b-lawlor** [comment]
In case anyone else has this issue, there is one more utcnow() you need to change so that the OLD status works properly in the html page.
Find it in `_get_datestring(self)` in this file:
[(https://github.com/jamesoff/simplemonitor/blob/master/Loggers/file.py)]
