### ISSUE TITLE
Could not open requirements file

### ISSUE THREAD

**Issue by Barna-154** [jamesoff/simplemonitor#545]
i am trying to build a docker image from the monitor.Dockerfile and its throwing this error:

ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/code/requirements.txt'
The command '/bin/sh -c pip install --no-cache-dir -r "$DOCKER_ROOT"/requirements.txt' returned a non-zero code: 1

**Comment by jamesoff** [comment]
Hi! I had a look at the docker stuff; it's mostly docker-compose oriented I think (it was a contribution, I don't use docker much). However, I tidied it up a bit and added a README in the docker directory with some pointers. I've successfully built a tested a container (and the docker-compose stack) with the current state so hopefully it'll work for you. (Take it from the `develop` branch.)

Hope that helps.

**Comment by Barna-154** [comment]
it worked fine thanks eyy
