### ISSUE TITLE
Don't log monitor failures to syslog unless the syslog alerter is configured

### ISSUE THREAD

**Issue by jayennis22** [jamesoff/simplemonitor#547]
As currently implemented, failure of systems being monitored cause simplemonitor to write my local syslog with ERROR messages like: 
`ERROR (simplemonitor) monitor failed: xxxx (Got status '403 Forbidden' instead of [200])
`
Currently, there is no configuration I can make to change this and syslog can be overrun with such messages.  

Since there is a syslog alerter, I recommend that monitor failures only be logged to syslog when that alerter is configured.

**Comment by jamesoff** [comment]
SimpleMonitor doesn't write to syslog other than via the syslog alerter. The message you're seeing is written to stdout/err (I forget which). How are you running it? Is the tool that's running it sending stdout/err to syslog for you?

You can prevent those messages from being written by passing `-q` or `--log-level=critical` on the command line.

**Comment by jayennis22** [comment]
On further study, I can see that simplemonitor doesn't configure a logging destination, python logging defaults its output to console/stderr, and that output is being captured to syslog by systemd.  So yes, directing stderr elsewhere is a good workaround.  I also see that there is a -q option which sets the logging level to critical.  Also a good workaround.

Thanks for your help.

**Comment by jamesoff** [comment]
No worries. If something like having the Python logging redirectable to a file would be useful, let me know. Been in two minds about if it's worth implementing :)
