### ISSUE TITLE
Multiple hosts with same monitor definition and network logging

### ISSUE THREAD

**Issue by robcza** [jamesoff/simplemonitor#55]
I have an issue with a setup, where I have central monitor host generating a status page and multiple hosts monitoring diskspace (the monitor is called "diskspace" on all the hosts)
It seems that the central monitor uses just the last information it receives from the individual hosts and it displays just a single line with diskspace status, though there is about 20 hosts. The host information in the status page changes from time to time showing different information from different hosts, but never more hosts at the same time.

Do I have to have different monitor names for every host? If yes, would it be possible to use environment variables in the configuration? The motivation behind is, the hosts are automatically provisioned by the docker container of simplemonitor and I'm not able to prepare unique image for every host.

**Comment by jamesoff** [comment]
Yeah, it's because it just uses the monitor name as the key globally. I'll make it so you can pull some environment variables in. Would you want arbitrary environment variables, or just some specific ones like $HOSTNAME to be available?

**Comment by robcza** [comment]
$HOSTNAME in the monitor name would solve the situation we have, but general support for environment variables would make simplemonitor super-usable in docker environment.

**Comment by jamesoff** [comment]
I can do that; how does `%env:name_of_env_variable%` sound? like `%env:HOSTNAME%`

**Comment by robcza** [comment]
That is perfect and should cover most of the use cases if available to use in both monitor names, configuration attributes, etc. Basically anywhere in both config files.

**Comment by jamesoff** [comment]
@robcza Give that branch a go?

BTW when testing, I realised `$HOSTNAME` is a shell variable not an environment one, so you may want to do something like
`HOSTNAME=$(hostname) python monitor.py ...`

**Comment by robcza** [comment]
I wasn't successful with using the env in the monitor names
Such configuration:
```
[diskspace-%env:HOSTNAME%]
type=diskspace
partition=/
limit=10G
```

Results in:
```
8/8/2017 10:12:52 AMSimpleMonitor v1.7
8/8/2017 10:12:52 AM--> Loading main config from monitor.ini
8/8/2017 10:12:52 AM--> Loading monitor config from monitors.ini
8/8/2017 10:12:52 AMAdding diskspace monitor diskspace-%env:HOSTNAME%
```

And status
```
diskspace-%env:HOSTNAME% | OK | tools-monitor-host-14 |   |   |   | 37.31GiB free (75%) |   |   | 54
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
```

The env variable seems to be set properly
```
# echo $HOSTNAME
monitor-host-1
```

Is the env parsing limited to particular attributes?

**Comment by jamesoff** [comment]
Oops, forgot to override the function for that! I'll fix that and update the branch.

**Comment by jamesoff** [comment]
Ok, try now :)

**Comment by robcza** [comment]
Supergood :)
Works and I can monitor the whole docker infrastructure through a single status page. Can I buy you beer?
```
8/8/2017 11:02:44 AMSimpleMonitor v1.7
8/8/2017 11:02:44 AM--> Loading main config from monitor.ini
8/8/2017 11:02:44 AM--> Loading monitor config from monitors.ini
8/8/2017 11:02:44 AMAdding diskspace monitor diskspace-monitor-host-1
```
```
diskspace-monitor-host-1 | OK | tools-monitor-host-1 |   |   |   | 200 OK in 0.01s |   |   | 27
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
```

**Comment by jamesoff** [comment]
Glad it works! I always accept beer, but that's just a general thing and not specifically related to writing code ;)
