### ISSUE TITLE
Update docs to suggest use of bash -c for commands if e.g. piping is required

### ISSUE THREAD

**Issue by jamesoff** [jamesoff/simplemonitor#58]
Reported by @poblabs on IRC, a `fail_command` such as 

`/usr/bin/mailx -A gmail -s "Failure: monitor {name} has failed." email@address <<<"The simplemonitor for {name} has failed.\n\nTime: {failed_at}\nInfo: {info}\n"`

does not work correctly.

**Comment by poblabs** [comment]
If in testing you don't have a gmail account configured on mailx, you can remove the `-A gmail` from the command.

**Comment by jamesoff** [comment]
Revisiting this, I think the issue is the use of the of the triple-less-than redirect, which is a bashism and SimpleMonitor just executes the commands directly (i.e. not via a shell).

It all worked ok when invoked as `bash -c "printf ... | mailx ..."` right? Maybe I just need a note to that effect in the docs for now.

**Comment by poblabs** [comment]
Yes, thanks to your clue on calling bash it worked. I know this is a Python script but for some reason in my head thought the commands were calling bash already. 

I ended up using this method below, and so far so good!

```
fail_command=/bin/bash -c "/usr/bin/printf \"The simplemonitor for {name} has failed on {hostname}.\n\nTime: {failed_at}\nInfo: {info}\n\" | /usr/bin/mailx -A gmail -s \"PROBLEM: simplemonitor {name} has failed on {hostname}.\" email@address"

success_command=/bin/bash -c "/usr/bin/printf \"The simplemonitor for {name} is now successful on {hostname}.\n\" | /usr/bin/mailx -A gmail -s \"RECOVERY: simplemonitor {name} is successful on {hostname}.\" email@address"
```
