### ISSUE TITLE
success_command is running in excess

### ISSUE THREAD

**Issue by poblabs** [jamesoff/simplemonitor#59]
As mentioned in #58 where I am using `/bin/bash` to email me on `fail_command` and `success_command`, I am noticing that I get 1 fail command email which is expected, but on success command email I am receiving 4 of them. 

I think the expected behavior should be to receive only 1? Am I missing something? 

Thanks!

**Comment by jamesoff** [comment]
It is not, I'll have a look. Is this using the threading version or my master branch? Do you just have one monitor which has the fail/success commands defined?

**Comment by poblabs** [comment]
I think I'm using your master branch. 

I have 2 monitors defined, one is a `host` and another is a `http`. The excessive emails appear to be with the `http` check.

**Comment by jamesoff** [comment]
Can't reproduce it with this config:

```
~/src/simplemonitor % cat tests/monitor-59.ini
[monitor]
monitors=tests/monitors-59.ini
interval=5

[reporting]
alerters=e

[e]
type=execute
fail_command=echo failed {failed_at}
success_command=echo success {failed_at}
~/src/simplemonitor % cat tests/monitors-59.ini
[test]
type=fail
fail_command=echo failed
success_command=echo success
```

```
~/src/simplemonitor % python monitor.py -f tests/monitor-59.ini -d
SimpleMonitor v1.7
--> Loading main config from tests/monitor-59.ini
--> Loading monitor config from tests/monitors-59.ini
Adding fail monitor test
--> Loaded 1 monitors.

Adding execute alerter e

--> Starting... (loop runs every 5s) Hit ^C to stop

Starting loop: ['test']
Trying: test
error_count = 0, interval = 5 --> 0
Fail: test (This monitor always fails.)

failed 2017-08-25 20:33:56

Starting loop: ['test']
Trying: test
error_count = 1, interval = 5 --> 1
Fail: test (This monitor always fails.)


Starting loop: ['test']
Trying: test
error_count = 2, interval = 5 --> 2
Fail: test (This monitor always fails.)


Starting loop: ['test']
Trying: test
error_count = 3, interval = 5 --> 3
Fail: test (This monitor always fails.)


Starting loop: ['test']
Trying: test
error_count = 4, interval = 5 --> 4
Fail: test (This monitor always fails.)


Starting loop: ['test']
Trying: test
error_count = 5, interval = 5 --> 0
Passed: test

success 2017-08-25 20:33:56

Starting loop: ['test']
Trying: test
error_count = 0, interval = 5 --> 0
Fail: test (This monitor always fails.)

failed 2017-08-25 20:34:26

Starting loop: ['test']
Trying: test
error_count = 1, interval = 5 --> 1
Fail: test (This monitor always fails.)

^C
--> Quitting.
--> Finished.
```

**Comment by jamesoff** [comment]
If that looks similar enough to your config which is behaving wrong, I guess I'll mock up a HTTP server which passes/fails the test on demand :)

**Comment by poblabs** [comment]
Sorry for delay - was away for the weekend! I'll do a little bit of testing with verbose mode and and paste what it shows.

**Comment by poblabs** [comment]
I tested this a bunch last night and a little bit today. The multiple executions seem to be happening when `gap=300` is in the `http` type. If I remove it, then I get a more reliable 1:1 execution ratio on fail`:`success. 

With the `gap` config in I get about 1 fail and 4 or 5 success executions. 

Attached is a photo of my inbox showing 1 failure and the 5 successes. 

My config is:
`monitor.ini`

```
[monitor]
interval=60
```

`monitors.ini`

```
[basecamp-ping]
type=host
host=my.example.com
tolerance=2

[basecamp-nagios]
type=http
url=http://my.example.com:8080
gap=300
depend=basecamp-ping
```

![simplemonitor](https://user-images.githubusercontent.com/3484775/29785018-0e7ca188-8bf4-11e7-8268-c19bb2029954.png)

**Comment by jamesoff** [comment]
Cool, thanks - that's useful stuff. I can sort of picture how the `gap` stuff may mess up the success execution, especially since you say you're getting roughly 300/60 duplicates. Been a while since I looked at that code, time to suit up :)

**Comment by jamesoff** [comment]
@poblabs could you give that branch ^^^ a go and see if it fixes the problem for you (and doesn't introduce any additional ones)?

It makes my little test case work correctly at least :)

**Comment by poblabs** [comment]
So far so good! I'll keep it going for the next couple of days to see

**Comment by poblabs** [comment]
Everything still seems to be in proper working order after a few more tests. I think we can close this ticket. Thanks again for the quick update!
