### ISSUE TITLE
SMTP Auth Error for mail Alerts 

### ISSUE THREAD

**Issue by Barna-154** [jamesoff/simplemonitor#594]
when i use the mail alert i get the following error and i dont know how i can go about it:

2020-07-16 12:42:15    ERROR (simplemonitor.alerter-email) couldn't send mail
Traceback (most recent call last):
  File "/home/ahfoz/.local/lib/python3.8/site-packages/simplemonitor/Alerters/mail.py", line 70, in send_alert
    server.login(self.username, self.password)
  File "/usr/lib/python3.8/smtplib.py", line 700, in login
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.

i have set my monitor.ini as follows:
[mail]
type=email
host=smtp.gmail.com
from=mysendingemail@gmail.com
to=myreceivingemal@gmail.com
username=mysendingemail@gmail.com
password=myemailpassword
only_failures=1

**Comment by jamesoff** [comment]
Could you try adding `ssl=starttls` to the configuration for it (the section you posted above)?

**Comment by Barna-154** [comment]
it worked. you awesome james you rock

**Comment by jamesoff** [comment]
Great, and thanks :)
