### ISSUE TITLE
Alerter Time Periods do not support timezone

### ISSUE THREAD

**Issue by jayennis22** [jamesoff/simplemonitor#595]
Alerters now support a tz configuration variable which controls the timezone used in the messages, but as far as I can see, the alerter time periods do not use it.  It would be very nice if time periods would obey tz as well so that I don't have to remember to go and reconfigure alerter time periods every time my locality goes on and off daylight savings time.

Thanks!

**Comment by jamesoff** [comment]
Yes, that would make sense wouldn't it :)

**Comment by jamesoff** [comment]
@jayennis22 I've merged a branch to `develop` which adds a `times_tz` option to Alerters, which specifies the TZ the two times values should be interpreted in. Let me know if that works for you.

**Comment by jayennis22** [comment]
Your fix works well.  Thanks very much!
