### ISSUE TITLE
All monitors should support an "enable" option

### ISSUE THREAD

**Issue by jayennis22** [jamesoff/simplemonitor#614]
Sometimes I need to take a monitor out of service for a while and I don't want to delete it.   I could comment it out, but it would be so much cooler if I could just add the option "enable=0" (or "disable=1") and have the monitor still show up in my html status page as "disabled".

Thanks!

**Comment by jamesoff** [comment]
This would be useful for my pkgaudit monitors which have been failed since like July because the FreeBSD pkg isn't getting fixed :)

**Comment by jamesoff** [comment]
@jayennis22 There's an initial version of this on the `feature/disable` branch. You can use `enabled=0` on a monitor to disable it, and it should stop being checked, and show up as "DISABLED" on the HTML page. Could you see if it works right for you?

**Comment by jayennis22** [comment]
@jamesoff Awesome!  It does just what I need and I see no issues.  Thanks very much!
