### ISSUE TITLE
Which file does the `  -f CONFIG, --config CONFIG configuration file` refer to?

### ISSUE THREAD

**Issue by jamesoff** [jamesoff/simplemonitor#615]
Bit related, which file does the `  -f CONFIG, --config CONFIG configuration file` refer to? Can I configure both paths somehow, or is one inherited from the other (e.g. pass one, and it'll look for the other in the same folder)? I'm a bit confused.

_Originally posted by @jasonmadigan in https://github.com/jamesoff/simplemonitor/issues/215#issuecomment-682490495_

**Comment by jamesoff** [comment]
Hi @jasonmadigan,

`-f` refers to the "main" config file, not the one with monitors in. You can specify the monitors file to load in the main file. For example, if in `other.ini` you have

```
[monitor]
interval=60
monitors=other-monitors.ini
```

Then you can use `simplemonitor -f other.ini`, which will then also load monitors from `other-monitors.ini`. I use this technique for testing things out, have a look in here: https://github.com/jamesoff/simplemonitor/tree/develop/tests

Hope that helps.

**Comment by jasonmadigan** [comment]
ah, that makes sense. wasn't aware the monitors could be configured via the main config file. thank you!
