### ISSUE TITLE
mqtt logging - home assistant discovery

### ISSUE THREAD

**Issue by Zeethulhu** [jamesoff/simplemonitor#624]
The hass option for mqtt logging is not working with Home Assistant.

SimpleMonitor v1.10.0
Home Assistant 0.115.0

The published content to mqtt broker does not meet the expected format for Home Assistant to discover.
https://www.home-assistant.io/docs/mqtt/discovery/

SimpleMonitor currently publishes the following to mqtt broker.
> homeassistant/binary_sensor/simplemonitor_Pfsense Gateway/config {"name": "Pfsense Gateway"}

HomeAssistant will only successfully discover with the following mqtt topic and message/payload
> homeassistant/binary_sensor/simplemonitor_Pfsense_Gateway/config {"name": "Pfsense Gateway", "state_topic": "homeassistant/binary_sensor/simplemonitor_Pfsense_Gateway/state"}

Please note the inclusion of state_topic in the payload and replacing the whitespace in "simplemonitor_Pfsense Gateway" with an underscore.

A nicety might be to also include device_class as "connectivity" in the payload to change the default icon in Home Assistant.
(Binary Sensor Device Class list and icons viewable here; https://www.home-assistant.io/integrations/binary_sensor/ )

> homeassistant/binary_sensor/simplemonitor_Pfsense_Gateway/config {"name": "Pfsense Gateway",  "device_class": "connectivity", "state_topic": "homeassistant/binary_sensor/simplemonitor_Pfsense_Gateway/state"}

**monitor.ini content**

> [monitor]
> interval=60
> monitors=/config/monitors.ini
> 
> [reporting]
> loggers=logfile,sqlite,json,mqtt
> 
> [logfile]
> type=logfile
> filename=/logs/log.log
> only_failures=1
> 
> [sqlite]
> type=db
> db_path=/logs/log.sql
> 
> [json]
> type=json
> filename=/logs/log.json
> 
> [mqtt]
> type=mqtt
> host=192.168.1.122
> hass=true

**Comment by jamesoff** [comment]
Thanks for the report. The mqtt logger was contributed by a third party; I don't use it. I'm happy to try fixing it up though. I assume it worked when it was contributed, do you know if Home Assistant changed their payload format at some point? (If so, I may need to support both formats for people who haven't upgraded?)

**Comment by jamesoff** [comment]
@Zeethulhu I had a go at fixing this on the `feature/hass-update` branch; could you please try? I ran a fresh HA install locally and my test monitors showed up after applying the fix.

I also added the `device_class` option, although at the moment it applies the same class to all monitors (as it's not possible to associate arbitary data with individual monitors).

**Comment by Zeethulhu** [comment]
Thanks @jamesoff !

I tested and some of the monitors are showing up in Home Assistant.

The monitors that contain spaces in the name don't appear.

Example Monitors.ini
```
[Netgear Access Point]
type=host
host=192.168.1.5

[Pfsense_Gateway]
type=host
host=192.168.1.1
```

**Netgear Access Point** will not appear in Home Assistant.
However **Pfsense_Gateway** will appear

This could be fixed by replacing the spaces in the MQTT topic with underscores.
From:
>homeassistant/binary_sensor/simplemonitor_Netgear Access Point/config

To:
>homeassistant/binary_sensor/simplemonitor_Netgear_Access_Point/config

Or... if Monitors.ini is not designed to have spaced in the monitor names, maybe a Warning can be raised and a note in the documentation.

**Comment by jamesoff** [comment]
Oh! I meant to fix that and completely forgot :( I was indeed going to replace spaces with underscores. I don't want to ban spaces in monitor names generally, but I might emit a warning from the mqtt logger that it's fixing them for you.

**Comment by jamesoff** [comment]
I've added a fix, but not tested it. I've updated the branch, if you wouldn't mind having a look?

**Comment by Zeethulhu** [comment]
They are all appearing now. :)

But the name of the monitor that shows up in Home Assistant contains the underscores.
The MQTT topics will need to contain the underscores, but the payload (which contains the name that home assistant displays) doesnt need to change.

The current branch posts this to the mqtt broker. 
`homeassistant/binary_sensor/simplemonitor_Netgear_Access_Point/config {"name": "Netgear_Access_Point", "state_topic": "homeassistant/binary_sensor/simplemonitor_Netgear_Access_Point/state"}`

Could you please remove the underscores from "name" in the payload.

`homeassistant/binary_sensor/simplemonitor_Netgear_Access_Point/config {"name": "Netgear Access Point", "state_topic": "homeassistant/binary_sensor/simplemonitor_Netgear_Access_Point/state"}`

**Comment by jamesoff** [comment]
Apologies, misunderstood. Pushed another commit to change the payload back.

**Comment by Zeethulhu** [comment]
They are all appearing now and look great.
The `device_class` is working too!

I watched the the MQTT and the initial post containing the config payload is working, and so is the first **state** topic.
However all the following state topics still contain spaces.

First config topic post with payload
`homeassistant/binary_sensor/simplemonitor_Netgear_Access_Point/config {"name": "Netgear Access Point", "state_topic": "homeassistant/binary_sensor/simplemonitor_Netgear_Access_Point/state", "device_class": "power"}`

First state topic post
`homeassistant/binary_sensor/simplemonitor_Netgear_Access_Point/state ON`

But the the following state posts still contain spaces in the MQTT topic
`homeassistant/binary_sensor/simplemonitor_Netgear Access Point/state ON`

**Comment by jamesoff** [comment]
Ah yes, I see my error. Pushed an update to the branch for you.

**Comment by Zeethulhu** [comment]
Thanks @jamesoff !  Looks like its all working!
