### ISSUE TITLE
mqtt logger (maybe all?) report failure even when monitors are not run

### ISSUE THREAD

**Issue by vvuk** [jamesoff/simplemonitor#636]
I've got a simple two monitor config; one a ping check that runs every 30 seconds, and one a speedtest that runs every 15 minutes (via `gap` on the monitor).  My verbose app output looks like this:

```
2020-11-19 22:59:10     INFO (simplemonitor) monitor passed: google-ping
2020-11-19 22:59:12     INFO (simplemonitor) monitor passed: wancheck
2020-11-19 22:59:46  WARNING (simplemonitor) monitor failed but within tolerance: google-ping
2020-11-19 22:59:46     INFO (simplemonitor) Not run: wancheck
2020-11-19 23:00:16     INFO (simplemonitor) monitor passed: google-ping
2020-11-19 23:00:16     INFO (simplemonitor) Not run: wancheck
```

etc.

If I configure a mqtt logger connected to Home Assistant, for the monitors that are not run, an "off" state is reported:

<img width="390" alt="Screen Shot 2020-11-19 at 3 04 13 PM" src="https://user-images.githubusercontent.com/194965/99734912-82924c00-2a78-11eb-94fd-c7a9390e2a74.png">

I have `only_failures=0` on the `mqtt` reporter as I'd like to have a heartbeat of the successes.  I think if a monitor is not run due to gap, no state should be logged?

**Comment by jamesoff** [comment]
Think I can see a bug in the code; you mention you're using Home Assistant so I assume you have `hass=1` in your config? If so, the code path for that doesn't check `only_failures`.

I'll push a fix for that on `develop` shortly, if that's good for you?

**Comment by jamesoff** [comment]
Scratch that, it's a slightly different problem I think :)

**Comment by jamesoff** [comment]
Ok so :) turns out that the mqtt logger doesn't properly support the `only_failures` option. It checks it, but it doesn't load it from the config (it's not a shared config option for all loggers, as it doesn't really make sense for all of them, like the HTML logger). So that's a bug.

I'm not sure not logging a monitor if it didn't run always makes sense, because it would disappear from whatever logging mechanism most of the time, but if what you want is a heartbeat with no continuous state between monitor executions I can add that as a config option. It would then log success/failure on the loop where it runs.

Note that even with a `gap` set, a failed monitor will run every loop so that it can post recovery as soon as possible. I'm guessing that isn't actually desirable for your speedtest monitor, so maybe you'd need an option on the monitor to stop that behaviour too?

Does that make sense?

**Comment by vvuk** [comment]
> I'm not sure not logging a monitor if it didn't run always makes sense, because it would disappear from whatever logging mechanism most of the time, but if what you want is a heartbeat with no continuous state between monitor executions I can add that as a config option. It would then log success/failure on the loop where it runs.

Hmm, I guess it depends on the logging mechanism; something like homeassistant or mqtt would know about the last state and when it was changed.  It wouldn't show up in text log output unless it was actually run, but I think that would be better than it showing up that it failed :)  But yes, the heartbeat with no continuous state is what I'm looking for I think; the continuity I'll leave to mqtt/homeassistnat/etc. to provide.

> Note that even with a gap set, a failed monitor will run every loop so that it can post recovery as soon as possible. I'm guessing that isn't actually desirable for your speedtest monitor, so maybe you'd need an option on the monitor to stop that behaviour too?

This is actually fine -- the speedtest monitor depends on the ping monitor, so it won't run if the link is completely down.  But if my horrible, horrible cable ISP is just performing poorly because they can't maintain the infrastructure properly, I don't really care if I'm hitting them with speedtests every few minutes until my bandwidth comes back.

**Comment by jamesoff** [comment]
@vvuk I pushed a branch `feature/heartbeat-logger` which adds that feature. Add `heartbeat=1` to your mqtt Logger and it should only log for monitors when they execute. Let me know if it works for you :)

**Comment by jamesoff** [comment]
@vvuk please let me know if that change is working correctly for you

**Comment by vvuk** [comment]
Sorry for the long delay -- holidays sucked up a lot of time :)  Will give it a try when I get a chance, but it might not be for a while.   I ended up just writing a bash script in a loop instead of simplemonitor; it was a bit overkill for what I needed, and it was easier to be able to put in monitor speed thresholds directly into the script instead of needing to hide them in "check" scripts for simplemonitor to call.

**Comment by jamesoff** [comment]
No worries, enjoy holidays :)

Whenever you have a chance to test it out, please let me know.
