### ISSUE TITLE
create Jira ticket with assignee

### ISSUE THREAD

**Issue by 3c2b2ff5** [jamesoff/simplemonitor#638]
Hi James,

I am trying to create a Jira ticket with assignee, I use `suproccess` to do so, since `smtplib` didn't work. In our setup we just send a Mail to a specific E-Mail address, which will create the ticket, the cc is the assignee, so a while ago after a lot of experimenting, subprocess worked just fine like this:
```
import os
import sys
import subprocess


from_addr = 'root'
to_addr = 'mail_one@local.domain, mail_two@local.domain'
message = "This E-Mail is sent with Python :)"
cmd = ["/usr/sbin/sendmail"]
cmd += ["-F", from_addr, "-f", from_addr]
cmd += ["-i", to_addr.encode("utf-8")]

try:
    p = subprocess.Popen(cmd, stdin=subprocess.PIPE)
except OSError:
    raise Exception("Failed to send the mail: /usr/sbin/sendmail is missing")

p.communicate(message)
if p.returncode != 0:
    raise Exception("sendmail returned with exit code: %d" % p.returncode)

sys.stdout.write("Spooled mail to local mail transmission agent\n")
```
of course I have the subject and some headers information somewhere else in my code. This is just to illustrate how I do it, note the comma separated E-Mail addresses.

I try to do the same with `simplemonitor`, I added a new parameter `jira` to `monitor.ini` and set it to `1` and made all needed modifications in `mail.py`, unfortunately the tickets are being assigned to the default assignee when I try to replace the `;` with a `,`,  in the `to` parameter, something like `addr = self.to_addr.replace(";", ", ")` and use the variable `addr` instead of `self.to_addr` in the `subprocess` code,it only works when I set `to=mail_one@local.domain, mail_two@local.domain` in `monitor.ini`, I don't know why is this happening, I am not a python expert, so basically I am using the `jira` parameter to use `suprocess` code with an `if` statement otherwise use the default `smtplib` code. I can still use something simple like this in the `mail.py` and get the same result,but I was hoping to get this in the best elegant way:
```
import os
from subprocess import Popen, PIPE

sendmail_path = "/usr/sbin/sendmail"
p = os.popen("%s -t" % sendmail_path, "w")
p.write("To: %s\n" % "mail_one@local.domain")
p.write("CC: %s\n" % "mail_two@local.domain")
p.write("Subject: Hello Python!\n")
p.write("\n")
p.write("This a test ticket")
stat = p.close()
```

Thanks a lot

**Comment by jamesoff** [comment]
Hey!

So if I'm understanding right, if the `mail` alerter supported a `cc` parameter as well as a `to` parameter, that would fix it for you? Was that the only issue with the smtplib version?

**Comment by 3c2b2ff5** [comment]
Hi,

as far as I can tell I didn't manage to make it work with `smtplib` at all, I could only make it work with `subprocess` but either with having the E-Mails in `to` parameter in `monitor.ini` comma separated with space, or by using the last trivial example in my original post. But even with `subprocess` the E-Mails should be already comma separated in the `monitor.ini` file I don't understand why using `replace()` or `", ".join(split())` doesn't work? I could try again with `smtplib`, maybe I missed something.

It seems to me that the `to`parameter should be comma separated either way,since trying to replace the `;` with `,`  doesn't work with `subprocess`, which is actually working if they are already comma separated.

**Comment by jamesoff** [comment]
Not sure what JIRA's requirements are around message formatting, and it's been a while since I worked with the mail/smtplib code properly, but I think this should do it:

```diff
diff --git a/simplemonitor/Alerters/mail.py b/simplemonitor/Alerters/mail.py
index 970426f..56018e9 100644
--- a/simplemonitor/Alerters/mail.py
+++ b/simplemonitor/Alerters/mail.py
@@ -25,6 +25,7 @@ class EMailAlerter(Alerter):
         self.to_addr = cast(
             str, self.get_config_option("to", required=True, allow_empty=False)
         )
+        self.cc_addr = cast(Optional[str], self.get_config_option("cc", required=False))
         self.mail_port = cast(
             int, self.get_config_option("port", required_type="int", default=25)
         )
@@ -47,6 +48,10 @@ class EMailAlerter(Alerter):
         message = MIMEMultipart()
         message["From"] = self.from_addr
         message["To"] = self.to_addr
+        envelope_to = self.to_addr.split(";")
+        if self.cc_addr:
+            message["CC"] = self.cc_addr
+            envelope_to.extend(self.cc_addr.split(";"))

         if alert_type == AlertType.NONE:
             return
@@ -80,7 +85,7 @@ class EMailAlerter(Alerter):
                         )
                         return
                 server.sendmail(
-                    self.from_addr, self.to_addr.split(";"), message.as_string()
+                    self.from_addr, envelope_to, message.as_string()
                 )
                 server.quit()
             except Exception:
```

I'm just setting up an SMTP endpoint to test it against.

**Comment by jamesoff** [comment]
That code worked for me, I received a mail with To: and CC set correctly:

```
[mail]
type=email
host=email-smtp.eu-west-1.amazonaws.com
from=james@jamesoff.net
to=james@jamesoff.net
cc=james-test@jamesoff.net
username=redacted
password=redacted
ssl=starttls
```

![Screenshot 2020-11-20 at 14 22 16](https://user-images.githubusercontent.com/5112771/99810698-02351f00-2b3c-11eb-91fe-5d06d78331ba.png)

**Comment by jamesoff** [comment]
Tested it with multiple addresses (`;`-separated) in the config and it didn't like that, but this version fixed it:

```diff
diff --git a/simplemonitor/Alerters/mail.py b/simplemonitor/Alerters/mail.py
index 970426f..953acfd 100644
--- a/simplemonitor/Alerters/mail.py
+++ b/simplemonitor/Alerters/mail.py
@@ -25,6 +25,7 @@ class EMailAlerter(Alerter):
         self.to_addr = cast(
             str, self.get_config_option("to", required=True, allow_empty=False)
         )
+        self.cc_addr = cast(Optional[str], self.get_config_option("cc", required=False))
         self.mail_port = cast(
             int, self.get_config_option("port", required_type="int", default=25)
         )
@@ -46,7 +47,11 @@ class EMailAlerter(Alerter):

         message = MIMEMultipart()
         message["From"] = self.from_addr
-        message["To"] = self.to_addr
+        message["To"] = self.to_addr.replace(";", ",")
+        envelope_to = self.to_addr.split(";")
+        if self.cc_addr:
+            message["CC"] = self.cc_addr.replace(";", ",")
+            envelope_to.extend(self.cc_addr.split(";"))

         if alert_type == AlertType.NONE:
             return
@@ -80,7 +85,7 @@ class EMailAlerter(Alerter):
                         )
                         return
                 server.sendmail(
-                    self.from_addr, self.to_addr.split(";"), message.as_string()
+                    self.from_addr, envelope_to, message.as_string()
                 )
                 server.quit()
             except Exception:
```

**Comment by 3c2b2ff5** [comment]
that is great, I will try to create now Jira tickets with assignee and let you know about the result.

**Comment by jamesoff** [comment]
Cool, you happy applying that diff above to your local copy or would you like it committed on a branch on github?

Save it and `patch -p1 < the-file.patch` should do it :)

**Comment by 3c2b2ff5** [comment]
either way is OK for me, I'll test first and then let you know. You can then decide how you would like to do it.

**Comment by jamesoff** [comment]
Cool, let me know if it works and I'll push a commit if it's successful

**Comment by 3c2b2ff5** [comment]
So, the `CC` works as it suppose to, so you could merge it any way, it is nice to have.
Unfortunately it doesn't work with Jira, the ticket assignee was still the default and not what I have in `cc`. I have to stop testing now because the default assignee is my boss and he keeps getting E-Mails about new tickets, even though he said I could continue, but it is Friday evening.
I'll get back to you on Monday.

I also really want to know why this work with Jira and what happens in Python internally with `smtplib`:
```
import os
from subprocess import Popen, PIPE

sendmail_path = "/usr/sbin/sendmail"
p = os.popen("%s -t" % sendmail_path, "w")
p.write("To: %s\n" % "mail_one@local.domain")
p.write("CC: %s\n" % "mail_two@local.domain")
p.write("Subject: Hello Python!\n")
p.write("\n")
p.write("This a test ticket")
stat = p.close()
```

Thanks James for your quick response. I wish a nice and healthy weekend.

**Comment by jamesoff** [comment]
That's very strange, I've not worked with JIRA's email-to-ticket stuff enough (or for years) to know what the differences might be and why it's not working the "smtplib way".

Thanks for trying it out, and have a good weekend :)

**Comment by 3c2b2ff5** [comment]
Hi James,

I made it work like the following but I have no clue how to implement it in your code:
```
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

me = "root@localhost"
to = "one@local.domain;two@local.domain"
cc = "three@local.domain"
msg_body = "This mail is sent with Python smtplib"

rcpt = to.split(";") + [cc]
msg = MIMEMultipart('alternative')
msg['Subject'] = "Test message"
msg['To'] = to
msg['Cc'] = cc
msg.attach(MIMEText(msg_body))
server = smtplib.SMTP("localhost")
server.sendmail(me, rcpt, msg.as_string())
server.quit()
```

As for Jira, the assignee is always the `cc` recipient, and you can have multiple `to` recipients, so basically there must be only one `cc` recipient and it doesn't matter how many `to` recipients. I am wondering how to implement this so it works for all kinds of scenarios, specially with this Jira issue.

Cheers

**Comment by jamesoff** [comment]
Looks like maybe it’s `Cc` instead of `CC` in the message headers. You could try my patch but change just that, see if that works?

**Comment by 3c2b2ff5** [comment]
Hi, weather `CC` nor `Cc` are in the headers and in `syslog` I only see the mail was sent to the two `to` recipients

**Comment by 3c2b2ff5** [comment]
I don't know what to say, it just doesn't respect the second object, it sends either to `to` object or to `cc` object, unless they are both in `to` or `cc`. I am really confused!

**Comment by 3c2b2ff5** [comment]
Hi James, it seems something went wrong with the patch. I applied the patch again and now it works. The last thing I could think of.  Thanks a lot

**Comment by 3c2b2ff5** [comment]
I even realized now that after the patch was correctly applied,  there is no need for the `cc` in my use case, I just need to make sure that the first `to` recipient is the Jira email and second `to` recipient is the assignee in Jira, all other `to` recipients will get the normal email. The only modification needed was the `replace(";", ",")` in the `to` object and the `split(";")` in `envelope_to` to create the recipients list.

Thanks again James

**Comment by jamesoff** [comment]
No worries, glad you got it working. I'm not clear on if the patch I shared worked as is or if you still needed to make some changes? Can you let me know and I'll get the code committed :)

**Comment by 3c2b2ff5** [comment]
The patch works perfectly fine. It was my bad. You can go ahead and commit. Thanks
