### ISSUE TITLE
rebuild pip package

### ISSUE THREAD

**Issue by 3c2b2ff5** [jamesoff/simplemonitor#639]
Hi James,

as the title suggest, would you please rebuild the pip package? I am using puppet to deploy and configure `simplemonitor`, of course I can patch every new installation manually, but having it already patched keeps it in the spirit of automation.

Thanks a lot.

**Comment by jamesoff** [comment]
[simplemonitor-1.11.0+dev.tar.gz](https://github.com/jamesoff/simplemonitor/files/5589666/simplemonitor-1.11.0%2Bdev.tar.gz)

Here you go, that's built from `develop` (`80dc01c`). You can build your own, btw, just run `python setup.py sdist` in the root of a copy of the code :) You'll get a .tar.gz in `dist/`.

**Comment by 3c2b2ff5** [comment]
Great. Thanks James.
