### ISSUE TITLE
https with Python 3

### ISSUE THREAD

**Issue by azlux** [jamesoff/simplemonitor#64]
In python3, into you requirement.txt, you need to add pyOpenSSL.

Without this library, requests is really slower with website how have strong cipher.

**Comment by jamesoff** [comment]
Thanks!

**Comment by jamesoff** [comment]
Hmm Python 2.7 doesn't like that... should it be just for Python 3?

I need to go out now, but I'll look harder at it later!

**Comment by jamesoff** [comment]
Looks like it was a transient problem with pip.

**Comment by azlux** [comment]
just for python3 (`sudo pip3 install pyOpenSSL`)
I almost never use python2.
