### ISSUE TITLE
Use of seq...

### ISSUE THREAD

**Issue by mrgfisher** [jamesoff/simplemonitor#641]
First, super useful system! Many thanks for building and sharing this, for what I was after this is perfect.

Would you be interested in a PR that adds Seq support as a logger? I.e. https://datalust.co/seq I can explain more about why and how, but thought would start with the if question first :-)

I have a working version, though if you would accept it I'll  need to add documentation updates etc..

**Comment by jamesoff** [comment]
Thanks, glad it’s useful :)

I’ve not come across Seq before but it looks interesting! I’d love a PR to add support for it.

**Comment by mrgfisher** [comment]
I find Seq super useful. First used in my 'day job', but have adopted it to log centrally all the various things I've built at home. I'll tidy the code, include updates to the docs (logging.md) and pop (here) some pics for the curious :-)

**Comment by mrgfisher** [comment]
PR created.

I'm not in anyway afiliated with Seq, but I do quite like it! Personally I use it in a docker image sitting on my nas - it just works. I can then easily see 'stuff' thats going on (or not) in a central place.

Attached is a screen shot of seq showing alerts created by simpleMonitor, the first is the startup, the second is informational (new word!) and then a fictious error. At the risk of sound like an advert, its then trivial to find and filter log entries via the UI.

As in the PR comment, all feedback welcome. I've tried to keep the logger simple enough to just work, hopefully inkeeping with the style of your other loggers.

Thanks again for making and sharing this!

![sampleSeqEntry](https://user-images.githubusercontent.com/6501882/100788611-372f5480-340d-11eb-91a4-3953104be4d6.png)

**Comment by jamesoff** [comment]
That looks really cool, it seems Seq is a bit ELK/Splunk-like? I'll have to give it a go when I have a bit more time.

I've popped a couple of comments on the PR, mostly code style type things.
