### ISSUE TITLE
Building Map with Leafletj

### ISSUE THREAD

**Issue by danieldh206** [jamesoff/simplemonitor#645]
This is really rough and I am still learning my way around git but I got the basics of building a display map going. 
header.html looks like this:
`<!DOCTYPE html>
<html lang="en">
	<head>
        <meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<title>_STATUS_@_HOST_ monitor</title>

		<link rel="shortcut icon" type="image/x-icon" href="docs/images/favicon.ico" />
		<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>
		<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="style.css" />
		<meta http-equiv="refresh" content="_INTERVAL_" />
		<script language="javascript" type="text/javascript">
			function too_old() {
				$("#refresh_badge").removeClass("d-none");
				$("#refresh_status").addClass("d-inline");
				$("#summary").removeClass("border-success border-danger");
				$("#summary").addClass("border-warning");
			}

			function check_age() {
				var generated = _TIMESTAMP_;
				var now = Date.parse(new Date()) / 1000;
				var diff = now - generated;
				if (diff > (_INTERVAL_ * 2)) {
					too_old();
				}
			}

		</script>
	</head>

	<body onload="check_age();">
		<div class="navbar navbar-light bg-light border-bottom _STATUS_BORDER_" id="summary">
			<div class="navbar-brand">SimpleMonitor</div>
			<div class="navbar-text d-none d-lg-block" id="updated">Updated at _NOW_ by _HOST_ (_VERSION_)</div>
			<div class="navbar-text" id="refresh_status"><span class="badge badge-warning d-none" id="refresh_badge">OUT OF DATE</span></div>
			<div class="navbar-text">_COUNTS_</div>
		</div>
	<div id="mapid" style="fill: 1440px; height: 960px;"></div>
	<script>

		var mymap = L.map('mapid').setView([47.421583, -120.263214], 7.5);
	
		L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZGFuaWVsZGgyMDYiLCJhIjoiY2szcmpnb2ExMDE2bDNkdDZyanYxcmF4bCJ9.qTBXFkdfzveo6kn3rsBmaQ', {
			maxZoom: 18,
			attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
				'<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
				'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
			id: 'mapbox/streets-v11'
		}).addTo(mymap);
	
		
	
	</script>
	<table class="table table-borderless table-striped table-hover table-sm">
		<tr>
			<th scope="col">Monitor</th>
			<th scope="col">Status</th>
			<th scope="col">Host</th>
			<th scope="col">Failed at</th>
			<th scope="col">VFC</th>
			<th scope="col">Up/downtime</th>
			<th scope="col">Detail</th>
			<th scope="col">Failures</th>
			<th scope="col">Last Failure</th>
			<th scope="col">Age</th>
			</tr>
`
in file.py I added `gps = name.split("/")[0]` to line 188 
and modified line 194 to `row = (f'<script>L.marker([{gps}]).addTo(mymap).bindPopup("{monitor_name}").openPopup()</script>;')`
In my monitors.ini file I put the GPS coordinates before name. [48.953,-122.423/test-name]

Once again sorry about not being very good with git and posting code in an issue.

**Comment by jamesoff** [comment]
Ooh interesting, like a geographical map of where things are? That’s cool!

If you’re working from a git clone, you can do `git diff` and paste that here to show all your changes :)

**Comment by danieldh206** [comment]
I will work on the git diff.

Yes, it is a geographical map. Still learning my way through Simplemonitor to figure out a better way to to make the code cleaner. 

![mapExample](https://user-images.githubusercontent.com/24887442/102921207-d65dcf80-4440-11eb-9d4e-c43919ff6ded.JPG)

**Comment by danieldh206** [comment]
I have my code up on my Github brand https://github.com/danieldh206/simplemonitor

**Comment by jamesoff** [comment]
That's cool. What are you monitoring, if I may ask? (Also how is it with ~380 monitors running? I have a branch which uses threads to run multiple monitors in parallel to reduce the time the loop takes to run, which may be useful for you.)

I think the main change I'd suggest is to have a `location` property of the Monitor (like `location=48.953,-122.423` in monitors.ini) rather than include it in the name, as there's other places the name would show up which might not work well with the coordinates embedded). Happy to help with that if you want :)

**Comment by danieldh206** [comment]
This is just a customer facing map and not high priority so speed is not an issue. The small server has no issue with 1 loop every 5 minutes. 
I would like to add a location property and only down sites show in the list underneath maps. I am also working on the color of the location pins, green for up and red for down. Leafletjs doesn't make setting the color of the pin easy. I picture has to be called up.

**Comment by danieldh206** [comment]
Got the map working. 
In the header.html file add:
	<body onload="check_age();">
		<div class="navbar navbar-light bg-light border-bottom _STATUS_BORDER_" id="summary">
			<div class="navbar-brand">SimpleMonitor</div>
			<div class="navbar-text d-none d-lg-block" id="updated">Updated at _NOW_ by _HOST_ (_VERSION_)</div>
			<div class="navbar-text" id="refresh_status"><span class="badge badge-warning d-none" id="refresh_badge">OUT OF DATE</span></div>
			<div class="navbar-text">_COUNTS_</div>
		</div>
	<div id="mapid" style="fill: 1440px; height: 960px;"></div>
	<script>

		var mymap = L.map('mapid', {
					center : [47.421583, -125.263214], 
					zoom : 7.6
		});
	
	
		L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZGFuaWVsZGgyMDYiLCJhIjoiY2szcmpnb2ExMDE2bDNkdDZyanYxcmF4bCJ9.qTBXFkdfzveo6kn3rsBmaQ', {
			maxZoom: 18,
			attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
				'<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
				'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
			id: 'mapbox/streets-v11'
		}).addTo(mymap);
	
		var markerIcon1 = L.icon({
			iconUrl: 'marker-single-up.png',
			popupAnchor:[11,2]
		});

		var markerIcon2 = L.icon({
			iconUrl: 'marker-single-down.png',
			popupAnchor:[11,2]
		});
	</script>

Also needed is creating the green and red png markers
In file.py add at line 192
if entry["status"] == True:
row = (f'<script>L.marker([{gps}], {{icon: markerIcon1}}).addTo(mymap).bindPopup("{monitor_name}").openPopup()</script>\n')
else:
row = (f'<script>L.marker([{gps}], {{icon: markerIcon2}}).addTo(mymap).bindPopup("{monitor_name}").openPopup()</script>\n')
