### ISSUE TITLE
SMS alerts using sms77

### ISSUE THREAD

**Issue by 3c2b2ff5** [jamesoff/simplemonitor#660]
Hi James,

Our standard monitoring system uses an in house smseagle for sms notifications, but we use sms77 for some random alerts as well. Is it possible to implement an alerter for sms77 as well?
Furthermore the documentation on github.io is not available any more, do you have the documentation some where else?

Best regards

**Comment by jamesoff** [comment]
Yeah that looks pretty straightforward, very similar to BulkSMS.

The docs being broken was a configuration issue, it's fixed now :)

**Comment by 3c2b2ff5** [comment]
Thanks James.

**Comment by 3c2b2ff5** [comment]
Hi James, any thing new about this?

**Comment by jamesoff** [comment]
I made a start on the code but haven't verified it yet. If you're happy to give it a go (and maybe fix it if doesn't work right against their API?) I'll push the branch up for you.

**Comment by 3c2b2ff5** [comment]
Will be happy to test it. Thanks a lot James

**Comment by jamesoff** [comment]
I've pushed it on the feature/sms77 branch. Please let me know if it works, and/or any patches needed :)

**Comment by 3c2b2ff5** [comment]
Oh, thank you very much James, sorry for the late response, I was just too busy the last week. Can you generate a patch file, because as you know I am installing via pip. Thanks a lot

**Comment by 3c2b2ff5** [comment]
OK, I managed to create the patch but according to [this](https://www.sms77.io/de/docs/gateway/http-api/sms-versand/) documentation site, the url should should be `https://gateway.sms77.io/api/sms`

**Comment by 3c2b2ff5** [comment]
after creating the new patch, I get the following error:
```
ERROR#033[0m (simplemonitor.alerter-sms77) Unable to send SMS: status code 900#033[0m
```
900 basically api_key error, but it works when enter the following to the browser:
```
https://gateway.sms77.io/api/sms?p=api_key&to=my_number&text=test%20message&from=sms77.de&return_msg_id=1
```
This documented [here](https://www.sms77.io/de/docs/gateway/http-api/sms-versand/)

**Comment by 3c2b2ff5** [comment]
with the following modification works:
```
+        params = {"text": message, "to": self.target, "from": self.sender, "p": self.api_key}
+
+        if not self._dry_run:
+            try:
+                r = requests.get(url, params=params)
```

ist it possible to add the parameter options to `monitor.ini` as well as the `limit` option

**Comment by 3c2b2ff5** [comment]
the `limit` and `only_failures` options work perfectly.

**Comment by jamesoff** [comment]
Cool, thanks for letting me know. I've pushed an update to that branch with your changes applied (hopefully). Let me know if it looks right :)

**Comment by 3c2b2ff5** [comment]
I have it live in our production environment. I did multiple tests and every thing work perfectly. Thanks James
