### ISSUE TITLE
Unable to Run simplemonitor 

### ISSUE THREAD

**Issue by Harkishen-Singh** [jamesoff/simplemonitor#67]
I recently recloned the project and then typed
`python2 monitor.py`
and it gave me this:

```
harkishen@harkishen-Aspire-A515-51G:~/Desktop/git works/simplemonitor$ python2 monitor.py 
SimpleMonitor v1.7
--> Loading main config from monitor.ini
--> Loading monitor config from tests/monitors.ini
Adding host monitor test1
Adding fail monitor test2
Adding command monitor command1
Adding command monitor command2
Adding command monitor command3
Adding command monitor command4
Adding http monitor http
--> Loaded 7 monitors.

Adding slack alerter slack

--> Starting... (loop runs every 5s) Hit ^C to stop
error_count = 0, interval = 5 --> 0
1
error_count = 1, interval = 5 --> 1
.error_count = 2, interval = 5 --> 2
error_count = 3, interval = 5 --> 3
.error_count = 4, interval = 5 --> 4
error_count = 5, interval = 5 --> 0
.error_count = 0, interval = 5 --> 0
error_count = 1, interval = 5 --> 1
.error_count = 2, interval = 5 --> 2
error_count = 3, interval = 5 --> 3
.error_count = 4, interval = 5 --> 4
^C
--> Quitting.
--> Finished.

```
It failed to run. Can anyone tell me whats going on?
This is my python version :   
```
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
```

**Comment by jamesoff** [comment]
Sorry, I missed this when you originally submitted it!

That looks like it's working fine to me. It's loading the monitors from the test configuration, which includes the `fail` monitor, which is what's outputting those `error_count` lines. (That monitor is really just for testing configurations.) The `1` is the output from a `recover_command` setting.

It then runs until you stopped it with ^C.

What makes you think it failed to run (so I can improve the output to be clearer)?

**Comment by Harkishen-Singh** [comment]
@jamesoff  , can u plz tell how do u run the software? its been long, since i last developed on this. 
As far as i remember, i ran the way its mentioned,but it gave an error.
Can u plz detail on the steps required to run the software??

**Comment by jamesoff** [comment]
`python monitor.py` is the minimum command.

`python monitor.py --help` will give you the list of options.

What error are you having?
