### ISSUE TITLE
DNS lookup monitor

### ISSUE THREAD

**Issue by vencax** [jamesoff/simplemonitor#7]
Hi, is somehow possible to check result of TXT DNS lookup?

**Comment by jamesoff** [comment]
Not yet, but I shall look into it.

**Comment by vencax** [comment]
import platform
import re
import os
import subprocess
import sys

from monitor import Monitor


class MonitorDNS(Monitor):
    """Monitor DNS server."""

    type = "dns"
    path = ""
    command = 'dig'

    def __init__(self, name, config_options):
        Monitor.__init__(self, name, config_options)
        try:
            self.path = config_options["path"]
        except:
            raise RuntimeError("Required configuration fields missing")
        if self.path == "":
            raise RuntimeError("Required configuration fields missing")
        
        if 'desired_val' in config_options:
            self.desired_val = config_options["desired_val"]
        
        self.params = [self.command]
        if "rectype" in config_options:
            self.params.append('-t')
            self.params.append(config_options["rectype"])
        self.params.append(self.path)
        self.params.append('+short')

    def run_test(self):        
        try:
            result = subprocess.Popen(self.params, stdout=subprocess.PIPE).communicate()[0]
            if result in None:
                result = 0
            if self.desired_val and result != self.desired_val:
                self.record_fail("resolved DNS record is unexpected %s != %s" % (self.desired_val, result))
                return False
            self.record_success()
            return True
        except Exception, e:
            self.record_fail("Exception while executing %s: %s" % (self.command, e))
            return False

    def describe(self):
        return "Checking that DNS recort %s is lookable." % self.path

    def get_params(self):
        return (self.path, )

**Comment by vencax** [comment]
something like that? not debugged, you would probably debug env already set up ...

**Comment by jamesoff** [comment]
Yeah, I did have a brief look at Python DNS libraries but there's nothing that grabs me as ideal, and I was trying to keep away from external dependencies as much as possible. Your code above looks like the right sort of thing.

**Comment by jamesoff** [comment]
Threw something together based on your work and it seems to do the right thing :)

(Renamed some of your config variables.)

Check the PR #9 for some notes.

**Comment by vencax** [comment]
I think you can merge it. I will then try it immediately ... thanks for your work!
