### ISSUE TITLE
Restarting Application with fail_command

### ISSUE THREAD

**Issue by victormleon** [jamesoff/simplemonitor#71]
I am trying to have the monitor watch a TCP connection and if it fails to restart the application that initially starts the connection. The way I am currently doing this is by running the .py file through command line using the `fail_command` in the `monitor.ini` file but once it does this, the monitor gets stuck in that application resulting in the monitor not watching the reconnected connection.

Any recommendations to have the monitor watch that reconnected connection? First thought is dealing with threading but wondering if there is another way.

**Comment by jamesoff** [comment]
It sounds like the application you're starting doesn't fork into the background, and simplemonitor will just wait for it to exit before it can continue.

If it doesn't have a built-in way to fork (you mention it's a .py script?) then you could write a wrapper script to launch it in the background, and then get simplemonitor to run that instead:

```sh
#!/usr/bin/env bash

/path/to/your/script.py &
```

You may also want `recover_command` on the monitor itself, which is like `fail_command` but tied to just that monitor. Execute alerters (and all alerters) will fire for each failed monitor, so if you have more monitors then the failure of any of them would try to start your script.
