### ISSUE TITLE
Ping is showing as 'passed' when the host is 'unreachable'

### ISSUE THREAD

**Issue by csjo** [jamesoff/simplemonitor#72]
Testing this on a windows machine on my home network.  I assume it's user error.

I set the monitors.ini to ping my chromecast ip

```
[chromecast-ping]
type=host
host="ip Address of my chromecast"
tolerance=1
```

and my monitor.ini to

```
[monitor]
interval=30

[reporting]
loggers=logfile

[logfile]
type=logfile
filename=monitor.log
only_failures=0
```

When I run it, the log file says

```
1518975287 chromecast-ping: ok (2.751s)
1518975320 chromecast-ping: ok (2.996s)
```

But if I were to ping the IP from the cmd line, I get a 'destination host unreachable.'

**Comment by jamesoff** [comment]
I wouldn't be so sure it's user error, Windows is a platform I'm using this on the least :)

Would you be able to share the output of the ping command when you run it? (Happy for you to redact IPs etc)

**Comment by csjo** [comment]
pinging 'IP Address of chromecast' with 32 bytes of data:
Reply from 'IP Address of computer': Destination host unreachable.


This repeats for every ping.  The chromecast is off, so I'm not exactly sure why I'm getting a destination host unreachable error, I would assume I would get 'request timed out'...so this may actually be my issue and I might have some strange routing issue.

**Comment by jamesoff** [comment]
I think maybe Windows reports that if it doesn't get an ARP response for the IP (assuming they're on the same subnet).

I'll fire up a Windows VM and give it a test.

**Comment by jamesoff** [comment]
@csjo that should fix it for you, on both master and python3 branches 🤞 reopen this if it doesn't work right still!
