### ISSUE TITLE
Runing on Windows

### ISSUE THREAD

**Issue by mikbro2021** [jamesoff/simplemonitor#764]
Getting an error running on Windows with Python 3.9.5

Traceback (most recent call last):
  File "C:\simplemonitor-release-1.11.0\simplemonitor\simplemonitor.py", line 15
, in <module>
    from .Alerters.alerter import Alerter
ImportError: attempted relative import with no known parent package

Command is python simplemonitor.py

**Comment by jamesoff** [comment]
Are you `cd`ing into the `simplemonitor` subdirectory? You don't need to do that, you should run `monitor.py` in the top-level directory.

Also, if you run `pip install .` in the that directory, you should get a `simplemonitor` (without the `.py`) command, if your PATH is set up correctly.

**Comment by mikbro2021** [comment]
Thanks. RTFM

**Comment by mikbro2021** [comment]
James

Query on hup file on a windows system. Does it look in the C:\simplemonitor-release-1.11.0 directory for the hup file or does it need the path in the monitor.ini? IF so, what is the format for the path/file string e.g. C:\simplemonitor-release-1.11.0\hup.txt?

Regards
Michael Brophy
Head of Project Engineering
Success is where preparation and opportunity meet
P: +353 1 293 8400
M: +353 85 1745818
Please send all support requests to ***@***.******@***.***>
E: ***@***.******@***.***>
A: St Joan's I.E, Ballymount, D22 NP49
W: www.welltelgroup.com<http://www.welltelgroup.com/>
***@***.***D769CA.DD003E90]<http://www.welltelgroup.com/>

At Welltel, we work flexibly and globally - so while it suits me to email now, I do not expect a response or action outside of your own working hours.

P Please consider the environment before printing this e-mail
*****************************************************
Welltel (Ireland) Ltd Email Disclaimer: "This e-mail and any files transmitted with it are confidential and are only for the use of the person to whom they are addressed. If you are not the intended recipient, you are hereby notified that any use, dissemination, forwarding, printing, copying or dealing in any way whatsoever with this e-mail is strictly prohibited. If you have received this e-mail in error, please reply to us immediately and delete the document. It is the recipient's duty to virus scan and otherwise test the enclosed information before using the information or loading attached files onto any computer system. Welltel (Ireland) Ltd does not warrant that the information contained in this e-mail is free from viruses, defects, errors, interception or interference. Any views expressed in this message are those of the individual sender, except where that sender specifically states them to be the views of Welltel (Ireland) Ltd"

**Comment by jamesoff** [comment]
If you just give a filename, or a relative path, it will look in/relative to the working directory when you run the script (so if your working directory is c:\simplemonitor-release-1.11.0 then it will look in there).

You can give an absolute path like you suggest, `hup_file=c:\somedir\hup.txt` will work.
