### ISSUE TITLE
Only Failures query

### ISSUE THREAD

**Issue by mikbro2021** [jamesoff/simplemonitor#789]
I am trying to set up an alert only for failures. I have added only_failure=1 and also tried only_failure=true but I still seem to be getting the up alert. Any guidance?

**Comment by jamesoff** [comment]
I think the setting name should be `only_failures` (you're missing the `s`).

**Comment by mikbro2021** [comment]
I am missing something allright. Is it '=1' or '=true' or does both work?

Regards
Michael Brophy
Head of Project Engineering
Success is where preparation and opportunity meet
Mobile: +353 85 1745818
Teams: Chat with ***@***.***>
Phone: +353 1 293 8450
Please send all support requests to ***@***.******@***.***>
E: ***@***.******@***.***>
A: St Joan's I.E, Ballymount, D22 NP49
W: www.welltelgroup.com<http://www.welltelgroup.com/>
***@***.***<http://www.welltelgroup.com/>

At Welltel, we work flexibly and globally - so while it suits me to email now, I do not expect a response or action outside of your own working hours.

P Please consider the environment before printing this e-mail
*****************************************************
Welltel (Ireland) Ltd Email Disclaimer: "This e-mail and any files transmitted with it are confidential and are only for the use of the person to whom they are addressed. If you are not the intended recipient, you are hereby notified that any use, dissemination, forwarding, printing, copying or dealing in any way whatsoever with this e-mail is strictly prohibited. If you have received this e-mail in error, please reply to us immediately and delete the document. It is the recipient's duty to virus scan and otherwise test the enclosed information before using the information or loading attached files onto any computer system. Welltel (Ireland) Ltd does not warrant that the information contained in this e-mail is free from viruses, defects, errors, interception or interference. Any views expressed in this message are those of the individual sender, except where that sender specifically states them to be the views of Welltel (Ireland) Ltd"

**Comment by jamesoff** [comment]
`=1` would be the canonical version but the config parser code should accept `=true` and `=yes` too

**Comment by jamesoff** [comment]
Did you get this resolved?

**Comment by mikbro2021** [comment]
Yes, my mistake

Regards
Michael Brophy
Head of Project Engineering
Success is where preparation and opportunity meet
Mobile: +353 85 1745818
Teams: Chat with ***@***.***>
Phone: +353 1 293 8450
Please send all support requests to ***@***.******@***.***>
E: ***@***.******@***.***>
A: St Joan's I.E, Ballymount, D22 NP49
W: www.welltelgroup.com<http://www.welltelgroup.com/>
***@***.***<http://www.welltelgroup.com/>

At Welltel, we work flexibly and globally - so while it suits me to email now, I do not expect a response or action outside of your own working hours.

P Please consider the environment before printing this e-mail
*****************************************************
Welltel (Ireland) Ltd Email Disclaimer: "This e-mail and any files transmitted with it are confidential and are only for the use of the person to whom they are addressed. If you are not the intended recipient, you are hereby notified that any use, dissemination, forwarding, printing, copying or dealing in any way whatsoever with this e-mail is strictly prohibited. If you have received this e-mail in error, please reply to us immediately and delete the document. It is the recipient's duty to virus scan and otherwise test the enclosed information before using the information or loading attached files onto any computer system. Welltel (Ireland) Ltd does not warrant that the information contained in this e-mail is free from viruses, defects, errors, interception or interference. Any views expressed in this message are those of the individual sender, except where that sender specifically states them to be the views of Welltel (Ireland) Ltd"

**Comment by jamesoff** [comment]
No worries, glad it's sorted :)
