### ISSUE TITLE
service status monitor flavors

### ISSUE THREAD

**Issue by vencax** [jamesoff/simplemonitor#8]
There is variety of flavors how to actuali check _nix service status but now only /usr/local/etc/rc.d/_ script is run. E.g. me on ubuntu based distro can check service \* status or /etc/init.d/\* status ...
I would suggest to have list of commands that are tried to run and if neither success, error is raised.

**Comment by jamesoff** [comment]
Having checked the code, the `rc` monitor type supports a `path` config option which tells it where the service script lives. It defaults to `/usr/local/etc/rc.d` but you can set it to `/etc/rc.d/` or similar as required.

This won't help if your using systemctl or some other system without compatibility scripts; I'll work on that.

For now, I'll update the documentation for the `rc` monitor type to be better.

**Comment by jamesoff** [comment]
I added a new monitor type, `unix_service`, which just shells out to `service X status` which makes it very portable (I hope). I'm successfully using it across Linux and FreeBSD now. Unless you have any strong thoughts otherwise, I'll close this ticket soon.
